### ISSUE TITLE
only maintenance mode

### ISSUE THREAD

**Issue by MrUnknownDE** [SergiX44/XBackBone#111]
**System Info**
+ PHP Version: 7.3.11
+ XBackBone Version: 3.0
+ Webserver: Apache, Debian 9, Plesk 18.0.21
+ Database backend: SQLite

Hi,

I have updated my "XBackBone" instance to 3.0. Unfortunately, I can no longer log in to my upload user because the page is in maintenance mode, only I have disabled the maintenance mode via Config.

Best Regards
Johannes | MrUnknownDE

**Comment by philw95** [comment]
I have the Same Problem.

**My Info:**
Update from version v2.6.4 to v3.0
- PHP Version: 7.3
- XBackBone Version: 3.0
- Webserver: Apache (Webhosting Netcup)
- Database backend: MySQL

**My Config:**
```
<?php
return array (
  'base_url' => 'https://xbackbone.XXXXXX.de',
  'displayErrorDetails' => true,
  'db' => 
  array (
    'connection' => 'mysql',
    'dsn' => 'host=XX.XX.XX.XXX;port=3306;dbname=XXXXXXXXX',
    'username' => 'XXXXXXXXX',
    'password' => 'XXXXXXXXX',
  ),
  'storage' => 
  array (
    'driver' => 'local',
    'path' => 'storage',
  ),
);
```

Error:
https://abload.de/img/yac17aot5nrwj77.png

**Comment by MrUnknownDE** [comment]
I think your problem is something else than what you mean. With me there were no problems with the updating. For me, only the bug is the instance in maintenance mode even though it is disabled.

**Comment by philw95** [comment]
Yes, I don't know if the update isn't even going through.

It all looks good. Except the upload that doesn't work.
<img width="567" alt="ERcvBXvdgJ" src="https://user-images.githubusercontent.com/27635979/69560006-4f26f980-0fab-11ea-8402-092b599999c0.png">

**Comment by MrUnknownDE** [comment]
Ohh!

**Comment by SergiX44** [comment]
> **System Info**
> 
> * PHP Version: 7.3.11
> * XBackBone Version: 3.0
> * Webserver: Apache, Debian 9, Plesk 18.0.21
> * Database backend: SQLite
> 
> Hi,
> 
> I have updated my "XBackBone" instance to 3.0. Unfortunately, I can no longer log in to my upload user because the page is in maintenance mode, only I have disabled the maintenance mode via Config.
> 
> Best Regards
> Johannes | MrUnknownDE

Did you updated the database?can you explain the steps to recreate that condition? I can't reproduce the problem


> Error:
> <img alt="yaC17AOt5n" width="569" src="https://user-images.githubusercontent.com/27635979/69555837-17688380-0fa4-11ea-883b-4c01081f32c3.png">
> Cannot connect to the database: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'remember_expire' [42000]

This is a different problem. There is a problem with the migration.

**Comment by MrUnknownDE** [comment]
> Did you updated the database?can you explain the steps to recreate that condition? I can't reproduce the problem

I have updated the database via the updater, that is via web browser. I do not use MYSQL but SQLITE

**Comment by SergiX44** [comment]
> > Did you updated the database?can you explain the steps to recreate that condition? I can't reproduce the problem
> 
> I have updated the database via the updater, that is via web browser. I do not use MYSQL but SQLITE

I've updated from a 2.6.6 instance without issue. Removing the maintenance => true fixed the problem? Have you tried to clean the system cache manually?

**Comment by MrUnknownDE** [comment]
No, the error still exists.

**Comment by SergiX44** [comment]
Try to navigate to your settings and update to the v3.0.1

**Comment by MrUnknownDE** [comment]
My Problem is fix! Thanks for quick resolving
