### ISSUE TITLE
Can't Update from 2.6.4 to 3.0

### ISSUE THREAD

**Issue by philw95** [SergiX44/XBackBone#112]
**System Info**
+ PHP Version: 7.3.11
+ XBackBone Version: 3.0
+ Webserver: I think Apache. (Webhosting by Netcup)
+ Database backend: Mysql

**Describe the bug**
I use the Update over the Webinterface.
When the update is done he will redirect me to the install page to Update the Database.
This doesn't work and I get the following error:
Cannot connect to the database: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'remember_expire' [42000]

**Screenshots**
<img width="569" alt="yaC17AOt5n" src="https://user-images.githubusercontent.com/27635979/69555837-17688380-0fa4-11ea-883b-4c01081f32c3.png">

**Logs**
[2019-11-25 16:30:03] app.INFO: User Philippe logged in. [] []

**My Config:**
```
<?php
return array (
  'base_url' => 'https://xbackbone.XXXXXX.de',
  'displayErrorDetails' => true,
  'db' => 
  array (
    'connection' => 'mysql',
    'dsn' => 'host=XX.XX.XX.XXX;port=3306;dbname=XXXXXXXXX',
    'username' => 'XXXXXXXXX',
    'password' => 'XXXXXXXXX',
  ),
  'storage' => 
  array (
    'driver' => 'local',
    'path' => 'storage',
  ),
);
```

**And i have test it with a new Config file:**
```
<?php

return [
    'base_url' => 'https://xbackbone.XXXX.de', // no trailing slash
    'db'       => [
        'connection' => 'mysql',
        'dsn'        => 'host=XX.XX.XX.XXX;port=3306;dbname=XXXXXXXXXX',
        'username'   => 'XXXXXXXXXX',
        'password'   => 'XXXXXXXXXX',
    ],
    'storage' => [
        'driver' => 'local',
        'path'   => './storage',
    ],
];
```

**Comment by philw95** [comment]
Here the Table migrations: (if you need)
<img width="328" alt="QVYtpU5V6c" src="https://user-images.githubusercontent.com/27635979/69580625-37646b00-0fd5-11ea-9ec5-fd15541529b7.png">

**Comment by SergiX44** [comment]
Try to navigate to your settings and update to the v3.0.1

**Comment by philw95** [comment]
Now Works. Thanks 😀
Nice 👍
