### ISSUE TITLE
Discord Pic/Video Preview

### ISSUE THREAD

**Issue by MrUnknownDE** [SergiX44/XBackBone#113]
Hey,
Since 3.0 Update, Discord gets via the conventional link no preview. But only via the RAW link. Would be cool if this feature can activate / rebuild.

Best regards 
Johannes | MrUnknownDE

**Comment by SergiX44** [comment]
Do you have Cloudflare (or similar proxies) enable on your instance? if yes there is something that allows robots to direct access the resources.
If still not working, maybe discord changed user agents that uses to get the previews.

**Comment by SergiX44** [comment]
Tested on Discord and works without issues.

![image](https://user-images.githubusercontent.com/4172890/69766005-7d0c6980-1176-11ea-9ca0-4cf4922b37f0.png)

**Comment by MrUnknownDE** [comment]
Okey. It works again. Discord just did not load it for me.
