### ISSUE TITLE
Config option "copy raw link to clipboard by default"

### ISSUE THREAD

**Issue by skinit** [SergiX44/XBackBone#117]
HI,

the copy link action copies the "show/view link" to the clipboard. I would like an option to "copy raw link" instead by default.

**Comment by SergiX44** [comment]
In the Sharex custom uploader config, just add a /raw to the return url.
https://github.com/SergiX44/XBackBone/issues/51#issuecomment-517337980

Display media in a fancy preview is one of the purposes of XBackBone, if only want a direct link, is not  easier using ftp directly?

**Comment by skinit** [comment]
Hi Sergi, I use XbackBone as an image store to embed images into markdown documents. That's why I need the raw format. I don't use sharex often. So every time I embed an image from XbackBone into a markdown document i have to add "/raw" manually. Your workaround does not work for me. It would be much easier to have an config option to force this by default.
Thank you

**Comment by evanmn** [comment]
I understand that this is not the solution that you are looking for, but you can manually change this easily for your instance alone (granted it will most likely get overwritten on updates).
## To change copy behavior on list view
1. Open `[resources/templates/dashboard/list.twig](https://github.com/SergiX44/XBackBone/blob/master/resources/templates/dashboard/list.twig)` in a text editor
2. add `/raw` to dataClipboardText on line 59.
3. Save file. Now when you click copy, it will append /raw automatically.
## Change copy behavior on individual viewer page
1. Open `[resources/templates/upload/public.twig](https://github.com/SergiX44/XBackBone/blob/ae23c080453ff869bbf108c1c5fd8836403aa445/resources/templates/upload/public.twig)` in a text editor
2. add `/raw` after `{{ url }}` but inside the quotes on line 20. It should look like this `"{{ url }}/raw"`.
