### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by TurboCheetah** [SergiX44/XBackBone#122]
**System Info**
+ PHP Version: 7.2
+ XBackBone Version: 3.0.2
+ Webserver: Nginx
+ Database backend: SQLite

I am getting an error 500 when I try to install.

1. Go to url/install
2. See error
**OR**
Manually install:
1. `cp config.example.php config.php && nano config.php` - I only changed the domain to my domain.
2. `php bin/migrate --install`

![](https://i.imgur.com/okxZLqp.png)

**Comment by SergiX44** [comment]
OK, but the error log?
Can you post nginx, php, etc logs because a 500 error can be literally anything.

**Comment by TurboCheetah** [comment]
Nginx Error Log: ```2020/01/25 12:17:47 [error] 11320#11320: *36 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: Compilation directory does not exist and cannot be created: /var/www/xbackbone//resources/cache/di. in /var/www/xbackbone/vendor/php-di/php-di/src/Compiler/Compiler.php:331
Stack trace:
#0 /var/www/xbackbone/vendor/php-di/php-di/src/Compiler/Compiler.php(176): DI\Compiler\Compiler->createCompilationDirectory('/var/www/xback....')
#1 /var/www/xbackbone/vendor/php-di/php-di/src/ContainerBuilder.php(177): DI\Compiler\Compiler->compile(Object(DI\Definition\Source\SourceChain), '/var/www/xback....', 'CompiledContain...', 'DI\\CompiledCont...', true)
#2 /var/www/xbackbone/bootstrap/app.php(62): DI\ContainerBuilder->build()
#3 /var/www/xbackbone/index.php(9): require_once('/var/www/xback....')
#4 {main}
  thrown in /var/www/xbackbone/vendor/php-di/php-di/src/Compiler/Compiler.php on line 331" while reading response header from upstream, client: 186.101.132.17, server: x.REDACTED, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "x.REDACTED"
```

**Comment by SergiX44** [comment]
Check the file permissions. Xbackbone should be owned by the Web server user. 
`Compilation directory does not exist and cannot be created` its pretty clear.
