### ISSUE TITLE
Raw link with filename at the End.

### ISSUE THREAD

**Issue by philw95** [SergiX44/XBackBone#123]
Would it be possible to set that when displaying the RAW image the URL ends with the filename?
Some pages check for this.

So for example: https://URL.com/folder/raw/IMAGE.png

Other uploader sites also have the image name at the end of RAW images.

Would that be possible?
Gladly also with an additional setting that must be activated.

**Comment by SergiX44** [comment]
Since 3.0, the raw url can be followed by the file extension:  https://URL.com/.../raw.png

**Comment by philw95** [comment]
Oh okay Nice. Thanks :)
