### ISSUE TITLE
[Question] 3.1 The theme is now re-applied after every system update.

### ISSUE THREAD

**Issue by yuvali1337** [SergiX44/XBackBone#136]
Just wanted to know what does this actually do. Does it reset the bootstrap css each update or does do something else

**Comment by SergiX44** [comment]
Now if you run the upgrade from the web ui, if you have installed a theme in the system settings, the theme after the update is reverted to the default bootstrap 4 theme. Now, after the update, the installer reinstall the theme you changed automatically.
