### ISSUE TITLE
Cannot embed in iframe

### ISSUE THREAD

**Issue by scharfschiesser** [SergiX44/XBackBone#146]
**System Info**
+ PHP Version: PHP 7.2.24
+ XBackBone Version: 3.0.2
+ Webserver: Apache 2.4.29
+ Database backend: SQLite3

**Describe the bug**
I have no issue embedding the application in the iframe itself, however when I try to login to xBackBone through the iframe it simply refreshes the page and clears the form. No error messages.

**To Reproduce**
Using the following iframe code:
`<iframe src="mywebsite" style="border: none; position: relative; visibility: visible; display: block; margin: 0px; padding: 0px; max-width: 100%; min-width: 200px;" height="800" width="100%"></iframe>`
Attempt to login.

**Expected behavior**
It is supposed to login and let me use the application.

**Screenshots**
-

**Logs**
`[2020-02-28 17:12:47] app.ERROR: Slim Application Error:
Type: Slim\Exception\HttpNotFoundException
Code: 404
Message: Not found.
File: /var/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 91
Trace: #0 /var/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(57): Slim\Middleware\RoutingMiddleware->performRouting(Object(GuzzleHttp\Psr7\ServerRequest))
#1 /var/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(132): Slim\Middleware\RoutingMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(class@anonymous))
#2 /var/www/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(89): class@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#3 /var/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(132): Slim\Middleware\ErrorMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(class@anonymous))
#4 /var/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): class@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#5 /var/www/vendor/slim/slim/Slim/App.php(208): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#6 /var/www/vendor/slim/slim/Slim/App.php(192): Slim\App->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#7 /var/www/index.php(10): Slim\App->run()
#8 {main}
View in rendered output by enabling the "displayErrorDetails" setting.
`

**Comment by SergiX44** [comment]
XBackbone set cookies using the samesite directive at Lax, it will work only if you are on the same (sub) domain. https://makandracards.com/makandra/71018-samesite-cookies
I strongly advise against removing the setting, as it exposes applications to csrf attacks.
