### ISSUE TITLE
[Question] Regarding the registration system 

### ISSUE THREAD

**Issue by yuvali1337** [SergiX44/XBackBone#147]
Will admins be able to enable / disable the registration system?
And will it have a registration-key function?

**Comment by SergiX44** [comment]
Yes.
Kind of, you can create an account and send a notification to the registered email account.

**Comment by yuvali1337** [comment]
> Yes.
> Kind of, you can create an account and send a notification to the registered email account.

Is it possible to create a kind of email invitation?
For example, creating an account from username and email only, then an email will be sent to the email and the user will have to set a password on first login.

**Comment by SergiX44** [comment]
Yes, it will be possible in the next release.
