### ISSUE TITLE
Upload canceled after exactly 30 seconds

### ISSUE THREAD

**Issue by electron2302** [SergiX44/XBackBone#157]
I suspect it has something to do with dropzone
[I found this on stackoverflow.com](https://stackoverflow.com/questions/46379917/dropzone-js-upload-with-php-failed-after-30-seconds-upload)

**Comment by electron2302** [comment]
Thanks for the quick response 👍 

when can I expect the improvement to be available in a new release ?

**Comment by SergiX44** [comment]
Ye in the release 3.1

**Comment by electron2302** [comment]
I really don’t want to annoy you too much but when can I expect 3.1 to come out ?

**Comment by SergiX44** [comment]
I can't give a real ETA, since i'm the only one who is working on this. The tag system and the LDAP auth  are still missing from 3.1
It will come out when it's ready™
