### ISSUE TITLE
404 after install

### ISSUE THREAD

**Issue by revilo951** [SergiX44/XBackBone#158]
**System Info**
+ PHP Version:PHP 7.2.24-0ubuntu0.18.04.3 (cli) (built: Feb 11 2020 15:55:52) ( NTS )
+ XBackBone Version:3.0.2
+ Webserver: [Apache/Nginx/...] apache2
+ Database backend: [SQLite/Mysql/...] sqlite

**Describe the bug**
run through install, redirects to /xbackbone/home which gives "not found"

apache2 access log:
10.210.19.1 - - [15/Mar/2020:18:56:09 +1100] "GET /xbackbone/home HTTP/1.1" 404 492 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36"

no other logs i can find show any errors

**Comment by SergiX44** [comment]
Is mod_rewrite enabled on apache?

**Comment by xMatador-Git** [comment]
Got the same problem with mod_rewrite enabled

**Comment by SergiX44** [comment]
Sorry but without any significant log, info, configuration how can I know where is the problem?
Double check file permissions, the base url is correct, apache is reading htaccess, etc

**Comment by xMatador-Git** [comment]
Nevermind i forgot to change the apache2.conf
From
```
<Directory /var/www/>
	Options Indexes FollowSymLinks
	AllowOverride None
	Require all granted
</Directory>
```

To
```
<Directory /var/www/>
	Options Indexes FollowSymLinks
	AllowOverride All
	Require all granted
</Directory>
```
Its working now
But still thank you and maybe its the solution for @revilo951
