### ISSUE TITLE
Have images pop up inline when pasting URL in messaging services?

### ISSUE THREAD

**Issue by ranasats** [SergiX44/XBackBone#160]
When you paste a URL from say IMGUR, the image is pulled into the inline chat by basically all messenger services (Facebook Messenger, WhatsApp, Discord, Slack, etc). This doesn't happen for the XBackBone server. Would it be possible to add support for this?

Thanks!

**Comment by SergiX44** [comment]
This is already implemented. It's working fine for discord, telegram, facebook. If you have cloudflare check the bot policies to access the image. With which service do you have issues?

**Comment by ranasats** [comment]
Ah oops, yes Discord shouldn't be on that list (the only one that works for me). WhatsApp doesn't do this, and neither does FBM. Is there a certain config issue I can look at?

**Comment by SergiX44** [comment]
![image](https://user-images.githubusercontent.com/4172890/76977265-63fe1300-6935-11ea-85f9-6a388cb6d00e.png)
![image](https://user-images.githubusercontent.com/4172890/76977423-9576de80-6935-11ea-9ff9-aa70048c5f95.png)
For facebook messenger its working. I've should added whattsapp in the next release.

If you have cloudflare, check the bot configuration.

**Comment by SergiX44** [comment]
Also, I've added the wa bot to the recognized bot, but even with imgur whatsapp doesn't display any image preview. I don't know what do you mean.
