### ISSUE TITLE
Preview only showing up once in a while (Discord)

### ISSUE THREAD

**Issue by antisozial** [SergiX44/XBackBone#167]
**System Info**
+ PHP Version: PHP 7.4
+ XBackBone Version: v3.0.2

Title pretty much says it, previews work one time, the other time it doesnt wanna work at all,

**Comment by antisozial** [comment]
![raw](https://user-images.githubusercontent.com/58865708/78192518-9a30ac00-7478-11ea-8672-f254e497635e.png)
Same link, only 1 time it showed up, same thing would happen if I'd send different screenshots

**Comment by SergiX44** [comment]
If you have cloudflare or something like that, check the bot policy, or try with the proxy disabled. Usually by default they block or limit bots like telegram, discord, fb etc.
