### ISSUE TITLE
invite codes

### ISSUE THREAD

**Issue by untuned** [SergiX44/XBackBone#178]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to be able to generate "Invite Codes" which people are required to use when registering, for a semi-private file host.

**Additional context**
One time use, can generate multiple at a time, and see previous codes with who generated and used them.

**Comment by SergiX44** [comment]
Is not really an invite code, but in the next stable 3.1, you can create accounts, and an invite to login email is sended to the associate emails.
