### ISSUE TITLE
themes

### ISSUE THREAD

**Issue by 0NinjaCat** [SergiX44/XBackBone#179]
**Is your feature request related to a problem? Please describe.**
Only one dark theme

**Describe the solution you'd like**
Add custom colors picker to the selected theme for example background color, navigation bar background, and text color
**Additional context**
n/a

**Comment by idblock** [comment]
The themes used come from https://bootswatch.com/ ; not created by @SergiX44

**Comment by SergiX44** [comment]
Also, you can always inject you css/js in the head from the system settings.
