### ISSUE TITLE
Choose a tag that is not used by anyone

### ISSUE THREAD

**Issue by idblock** [SergiX44/XBackBone#182]
**System Info**
+ PHP Version : 7.4.3
+ XBackBone Version : 3.1 RC3
+ Apache
+ MySQL

**Describe the bug**
When we choose a tag from the tag list and unfortunately there is no upload file that uses it, we come across a 500 error page, 

**To Reproduce**
1. Go to home
2. Click on tag button
3. Scroll down to 'choose a tag which is not used by any file 

**Expected behavior**

I think I just have an error message a little bit like a popup would be more interesting

**Screenshots**
![image](https://user-images.githubusercontent.com/26309538/78786692-7bb33f00-79a9-11ea-9ddc-c7529612701c.png)
![image](https://user-images.githubusercontent.com/26309538/78786929-d2b91400-79a9-11ea-8518-691e02e89172.png)

**Comment by SergiX44** [comment]
I'm not able to reproduce the error. Can you provide the exact steps, from the upload of the file to the error?
In general, in that list there should be no unused tags, in fact, if a tag is removed from all the media to which it is linked, it is deleted.

**Comment by idblock** [comment]
I sent several files via the "Upload with ShareX" option, the files obviously did not receive the automatic tag "Image", when I tested pressing the Tag button then IMAGE, I was brought back to a error 500, in itself nothing very serious and very common but must always warn and be ready: P

**Comment by idblock** [comment]
And I add that it's a shame, we can add tags but not delete them (unless it is planned)

**Comment by idblock** [comment]
![eglsp2QjqN](https://user-images.githubusercontent.com/26309538/78805332-91ccf980-79c1-11ea-95df-2623c5fe6639.gif)

**Comment by SergiX44** [comment]
You can delete tags right-clicking on them.

Can you send the logs about the error?

**Comment by idblock** [comment]
Oh okay ! Nice !

How can i did this ?

**Comment by idblock** [comment]
I add that none of my other uploads contain the tag "image"

**Comment by SergiX44** [comment]
Try to add the tag image and the remove it.

> Oh okay ! Nice ! (Maybe dropdown button to add tag that is used recurrently instead of having to write it down every time?)
> 
> How can i did this ?

Currently, the tag is linked when to the upload itself, may in the future can be expanded somehow.

**Comment by idblock** [comment]
> Try to add the tag image and the remove it.
> 
> > Oh okay ! Nice ! (Maybe dropdown button to add tag that is used recurrently instead of having to write it down every time?)
> > How can i did this ?
> 
> Currently, the tag is linked when to the upload itself, may in the future can be expanded somehow.

It works :) (I suspected a little to tell the truth but to see if it does not happen regularly!)

**Comment by SergiX44** [comment]
If you have the log of the error, please send it. I'll look into it.

**Comment by idblock** [comment]
![image](https://user-images.githubusercontent.com/26309538/78807118-e83b3780-79c3-11ea-8456-33fb5803549d.png)
