### ISSUE TITLE
Http 500

### ISSUE THREAD

**Issue by lebon1377** [SergiX44/XBackBone#185]
I was installing the new update through the dashboard and when the loading finished the website crashed and it started showing me Http 500.

**Comment by SergiX44** [comment]
Check if the ext zip is enabled.
To recover the installation, extract manually the files from the release zip, navigate to the /install and complete the upgrade.
Follow the issue template the next time.

**Comment by lebon1377** [comment]
Okie!

**Comment by lebon1377** [comment]
Its not working

**Comment by lebon1377** [comment]
Guess ill have to re install.

**Comment by SergiX44** [comment]
Please post some error logs.
Did you check that the php zip extension is enabled?

**Comment by lebon1377** [comment]
Yes

**Comment by lebon1377** [comment]
Its fine I already began the Re-Install Process:)

**Comment by SergiX44** [comment]
It could be useful to prevent the error from happening again in the future anyway.

**Comment by lebon1377** [comment]
Hey
