### ISSUE TITLE
Http 500

### ISSUE THREAD

**Issue by lebon1377** [SergiX44/XBackBone#186]
**System Info**
+ PHP Version: 7.1
+ XBackBone Version: Latest

**Describe the bug**
I am getting the error http 500 again when I reinstalled all files.

**Comment by lebon1377** [comment]
I am getting it again.

**Comment by lebon1377** [comment]
Warning: require(/home/vol14_5/epizy.com/epiz_25400938/cdn.lebyy.cf/htdocs/vendor/autoload.php): failed to open stream: No such file or directory in /home/vol14_5/epizy.com/epiz_25400938/cdn.lebyy.cf/htdocs/index.php on line 4

Fatal error: require(): Failed opening required '/home/vol14_5/epizy.com/epiz_25400938/cdn.lebyy.cf/htdocs/vendor/autoload.php' (include_path='.:/usr/share/pear/') in /home/vol14_5/epizy.com/epiz_25400938/cdn.lebyy.cf/htdocs/index.php on line 4

**Comment by SergiX44** [comment]
I've just tested the installation of the 3.1.rc6 with php 7.1, and it's working without errors.
Please check that all required php extensions required by xbackbone are enabled and check the file permissions.
The error you posted says that the application is unable to access the file in /vendor/autoload.php

**Comment by lebon1377** [comment]
Warning: require(/home/vol14_5/epizy.com/epiz_25400938/cdn.lebyy.cf/htdocs/vendor/autoload.php): failed to open stream: No such file or directory in /home/vol14_5/epizy.com/epiz_25400938/cdn.lebyy.cf/htdocs/index.php on line 4

Fatal error: require(): Failed opening required '/home/vol14_5/epizy.com/epiz_25400938/cdn.lebyy.cf/htdocs/vendor/autoload.php' (include_path='.:/usr/share/pear/') in /home/vol14_5/epizy.com/epiz_25400938/cdn.lebyy.cf/htdocs/index.php on line 4

**Comment by lebon1377** [comment]
Oh

**Comment by lebon1377** [comment]
![image](https://user-images.githubusercontent.com/45114019/78987050-76412a80-7b4a-11ea-9242-9152c4bca08b.png)
Theres no vendor folder infact on the repo

**Comment by Pe46dro** [comment]
You should pick a [release](https://github.com/SergiX44/XBackBone/releases) not the source code

**Comment by lebon1377** [comment]
Oh oof

**Comment by lebon1377** [comment]
Warning: require_once(/home/vol14_5/epizy.com/epiz_25400938/cdn.lebyy.cf/htdocs/vendor/composer/autoload_real.php): failed to open stream: No such file or directory in /home/vol14_5/epizy.com/epiz_25400938/cdn.lebyy.cf/htdocs/vendor/autoload.php on line 5

Fatal error: require_once(): Failed opening required '/home/vol14_5/epizy.com/epiz_25400938/cdn.lebyy.cf/htdocs/vendor/composer/autoload_real.php' (include_path='.:/usr/share/pear/') in /home/vol14_5/epizy.com/epiz_25400938/cdn.lebyy.cf/htdocs/vendor/autoload.php on line 5

**Comment by lebon1377** [comment]
I tried updating.

**Comment by SergiX44** [comment]
Check if all the files are correctly uplaoded. That's the same error again, the file /vendor/composer/autoload_real.php is not found or cannot be accessed

**Comment by yuvali1337** [comment]
Try clean installing and making sure all the folders permissions are right

**Comment by lebon1377** [comment]
Should I do 777 for perms?

**Comment by yuvali1337** [comment]
Yeah do that and also do 
chown -R www-data:www-data * 
If you're on ubunto.

**Comment by lebon1377** [comment]
Nope its on C-panel which is infinity free.

**Comment by lebon1377** [comment]
I am overwriting the files.

**Comment by yuvali1337** [comment]
Delete the whole folder and get the unzip the release on a clean site.

**Comment by lebon1377** [comment]
To make sure everything is proper, but filezilla and my host is damn slow it takes 1-2 hours for 20 mb files

**Comment by yuvali1337** [comment]
> To make sure everything is proper, but filezilla and my host is damn slow it takes 1-2 hours for 20 mb files

Then buy a vps its way faster and better for this kinda useage.

**Comment by lebon1377** [comment]
Ik, but this host has Infinite storage.

**Comment by yuvali1337** [comment]
> Ik, but this host has Infinite storage.

If it takes you 2hrs to upload 20mb i dont think infinity storage is worth for that slow of a host.

**Comment by SergiX44** [comment]
Be sure to also you have download the release zip and not the source zip: https://github.com/SergiX44/XBackBone/releases/download/3.1/release-v3.1.zip

**Comment by lebon1377** [comment]
yes

**Comment by yuvali1337** [comment]
> yes

You can get good eu servers cheap from netcup.de or vpsag.com

**Comment by lebon1377** [comment]
I just want it for a image server so itll be fine.
