### ISSUE TITLE
/raw gifs arent played on previews (discord)

### ISSUE THREAD

**Issue by yuvali1337** [SergiX44/XBackBone#187]
**System Info**
+ PHP Version:7.2.24-0ubuntu0.18.04.3
+ XBackBone Version:latest
+ Webserver: [Apache/Nginx/...]apache
+ Database backend: [SQLite/Mysql/...]sqlite

**Describe the bug**

**To Reproduce**
Get any GIF link
add /raw at the end on discord or any other program with previews
**Expected behavior**
GIF should be played and is not played.

**Screenshots**

![preview](https://carding.training/3019_NDP1F8CE3H.gif)

**Comment by idblock** [comment]
Oh yes, i have the same problem

**Comment by SergiX44** [comment]
I don't think it's a XBackBone issue, because the /raw is the exact same that is served at the normal url if a bot is found.
Try to put the file extension to /raw like /raw.gif

**Comment by yuvali1337** [comment]
> I don't think it's a XBackBone issue, because the /raw is the exact same that is served at the normal url if a bot is found.
> Try to put the file extension to /raw like /raw.gif

Yeah, you're right. you can close
