### ISSUE TITLE
Updating from 3.0.1 to 3.1.1 Cannot connect to the database: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'remember_selector' [42S21]

### ISSUE THREAD

**Issue by rossiscool123** [SergiX44/XBackBone#190]
**System Info**
+ PHP Version: 7.3
+ XBackBone Version: 3.0.1 Upgrading to 3.1.1
+ Webserver: Apache
+ Database backend: MySQL

**Describe the bug**
Error `Cannot connect to the database: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'remember_selector' [42S21]` when upgrading from 3.0.1 to 3.1.1 using the /install path

**To Reproduce**
1. Replace the 3.0.1 files with the 3.1.1 build
2. Go to https://domain.com/install
3. Update-Database
4. https://i.imgur.com/xjEUxOS.png

**Comment by SergiX44** [comment]
I've tried to upgrade from the 3.0.1 to the latest 3.1.1, but it doesn't gave me any error. You can try to connect the the database, and try to to drop the columns remember_selector`, `remember_token` and `remember_expire` if they exists, and try to update again.

**Comment by rossiscool123** [comment]
Perfect, fixed the issue completely, did have to Google how to drop tables since its something I've never had to do. Apart from that is fixed the issue. Hopefully, if someone else has this issue they can find it as well.

Thank you @SergiX44
