### ISSUE TITLE
After Update Uploads empty.

### ISSUE THREAD

**Issue by philw95** [SergiX44/XBackBone#191]
**System Info**
+ PHP Version: 7.3
+ XBackBone Version: 3.1.1
+ Webserver: Apache (Webhosting/Netcup)
+ Database backend: Mysql

**Describe the bug**
In MySQL the uploads table is empty after the update. I have try 3.1 and 3.1.1

**To Reproduce**

1. Replace the 3.0.1 files with the 3.1.1
2. Open https://domain.com/install
3. Update-Database
4. Now table uploads are empty

**Screenshots**
<img width="461" alt="UZZwWMUXXs" src="https://user-images.githubusercontent.com/27635979/79067502-03f25680-7cc0-11ea-89ba-f1658d821222.png">
<img width="570" alt="Px2RMSySZZ" src="https://user-images.githubusercontent.com/27635979/79067503-081e7400-7cc0-11ea-9d0f-2506b69fc727.png">

**Logs**
There's nothing in the logs.
Just that:
[2020-04-12 12:45:07] app.INFO: User XXXXX logged in. [] []
[2020-04-12 12:57:23] app.INFO: User XXXXX logged in. [] []

**Comment by SergiX44** [comment]
What do you see in the migration table?
The upload table isn't even right, there are several column missing. There is something in the webserver logs?

**Comment by philw95** [comment]
here my migration table:
<img width="406" alt="mDoff4BRKf" src="https://user-images.githubusercontent.com/27635979/79067833-a90e2e80-7cc2-11ea-8675-8edb273c46e2.png">

Cannot access the webserver log. It is a web hosting package.

**Comment by Pe46dro** [comment]
Does the storage folder have files inside?
Are you using external storage?

**Comment by philw95** [comment]
Yeah, all the files are still there.
No is in the storage folder from xbackbone.

**Comment by philw95** [comment]
Oh for the info a backup is available. :)

**Comment by SergiX44** [comment]
Can you try to recover the backup and try again to upgrade from the web ui?

**Comment by philw95** [comment]
i have try it with the Web UI and manual.
I can Try it again.

**Comment by philw95** [comment]
The same :(

Bevor:
<img width="745" alt="4CelSw58iB" src="https://user-images.githubusercontent.com/27635979/79070261-ec719880-7cd4-11ea-900c-2ea7d33b29af.png">

After:
<img width="442" alt="VkHKFKmWt4" src="https://user-images.githubusercontent.com/27635979/79070287-1c20a080-7cd5-11ea-8f80-16fd403cbf27.png">

**Comment by philw95** [comment]
Ahh I have webserver logs, but there are no errors:

<img width="828" alt="pNHAW1R3Ks" src="https://user-images.githubusercontent.com/27635979/79070853-943c9580-7cd8-11ea-9909-25be1099ebd7.png">

**Comment by SergiX44** [comment]
I think your database was corrupted before the release, if you was on the 3.0.1 version, in the user table should exists the columns remember_selector, remember_token and remember_expire, also, after the update, I don't see the new tables that should be present.

**Comment by SergiX44** [comment]
It seems that migrations starting from number 4 (https://github.com/SergiX44/XBackBone/tree/master/resources/schemas/mysql) have never been performed

**Comment by philw95** [comment]
No, the tables are there. I forgot to refresh the navigation panel.

Here the user table:
<img width="958" alt="NTC107pnZw" src="https://user-images.githubusercontent.com/27635979/79072573-05cd1180-7ce2-11ea-97a7-e212e917d5d9.png">

**Comment by philw95** [comment]
This is bevor update!

**Comment by philw95** [comment]
This from After Update:
<img width="959" alt="aBwnS81sqW" src="https://user-images.githubusercontent.com/27635979/79072662-7d9b3c00-7ce2-11ea-8bb9-ab16553963d6.png">

**Comment by SergiX44** [comment]
Ok, could you try to updating by replacing all files with the 3.1 release zip, then, replace the Migrator.php in the folder app/Database with the one i've attacched (renaming it), and then update.
[Migrator.php.txt](https://github.com/SergiX44/XBackBone/files/4466571/Migrator.php.txt)

**Comment by philw95** [comment]
Okay I'll try

**Comment by philw95** [comment]
Yeah. Now it runs.
<img width="746" alt="mapPY8Btoh" src="https://user-images.githubusercontent.com/27635979/79073137-23e84100-7ce5-11ea-828f-3849c5ce3653.png">

**Comment by philw95** [comment]
Gave you a donation once.
Nice work. :)

**Comment by SergiX44** [comment]
You storage folder path is probably a relative path, check that the path to the storage folder is an absolute path or could happen again in the upcoming releases. I'll also add a check in the installer to this specific edge case

> Gave you a donation once.
> Nice work. :)

Thank you, much appreciated.

**Comment by philw95** [comment]
Ah you mean in the Config file?
'path' => './storage',

**Comment by SergiX44** [comment]
Yes, replace the path with the absolute path.
I've updated the installer and should make this conversion at the next update, but for safety it update it first.
