### ISSUE TITLE
file uploading

### ISSUE THREAD

**Issue by 0NinjaCat** [SergiX44/XBackBone#194]
**System Info**
+ PHP Version: 7.2
+ XBackBone Version: v3.1.1
+ Webserver: LiteSpeed 
+ Database backend: Mysql

**Describe the bug**
I don't know if it is a bug, or it is my fault but when I try to upload something bigger than ~2 MB for example, 26 MB .zip file then it stuck at 100% of uploading and after like 2 minutes file upload just getting canceled.

**To Reproduce**
Just try to upload bigger than 10 MB .zip file

**Expected behavior**
IDK

**Screenshots**
I don't have

**Logs**
[14-Apr-2020 17:47:46 Europe/Warsaw] PHP Warning:  Error while sending QUERY packet. PID=1098423 in /home/u438257475/domains/nigger.lgbt/public_html/app/Database/DB.php on line 41

**Comment by SergiX44** [comment]
There is something wrong with your mysql installation about the packet max size, or something like that, thats not a problem related to xbackbone
