### ISSUE TITLE
Make a discord server!.

### ISSUE THREAD

**Issue by Lebyy** [SergiX44/XBackBone#201]
Hey there! I use XbackBone Regularly and I know there a lot of updates it's hard to keep a track of everything so I request you to create a discord server where we can get pinged for updates, I can help you making one Just add me Lebyy_Dev#3665.

**Comment by SergiX44** [comment]
I don't like Discord much, maybe I can make a slack group or a telegram group/channel.

**Comment by scharfschiesser** [comment]
I would love to join a slack or telegram group if you ever make one :)

**Comment by lebon1377** [comment]
> I don't like Discord much, maybe I can make a slack group or a telegram group/channel.

Sure!

**Comment by enescaglayan** [comment]
Yup it would be cool if we had discord server

**Comment by SergiX44** [comment]
https://discord.gg/ksPfXFbhDF
😃
