### ISSUE TITLE
CDN Support

### ISSUE THREAD

**Issue by camjac251** [SergiX44/XBackBone#208]
Would it be possible to support feeding file links over a subdomain rather than the root? I wanted to possibly use BunnyCDN for serving direct files for quick download speeds no matter where the user is.

They have two offerings available, the regular CDN that mirrors an endpoint so like `cdn.example.com/imagename.png` could serve `example.com/imagename.png` although I think you could also rewrite the permalinks too.
And their storage backend as well similar to B2/S3/Wasabi, but since it's hosted by them it would offer lower latency to their CDN.

They do have a flysystem module available https://packagist.org/packages/platformcommunity/flysystem-bunnycdn as well.

One thing that confuses me though about serving files. Can PHP serve the stored like static HTML headers that are served through a CDN? Would it be compatible with the video player framework?

**Comment by SergiX44** [comment]
XBackBone supports AWS S3, Google Cloud, Dropbox as remote storages services, just select that during the installation and all files would be stored remotely.

**Comment by camjac251** [comment]
I was curious about the CDN part. BunnyCDN operates better with their own storage and it'd be cheaper than S3, Google Cloud Storage and Dropbox.

Could also a subdomain function be supported? Like the above example?

**Comment by camjac251** [comment]
Do files get served directly to the web browser from the storage backend without going through the server running the webserver first?

**Comment by SergiX44** [comment]
No, the flysystem adapter are simply a different way to store files, so for the system is just a different way of saving and retrieving files. Also, the adapter you linked, doesn't support stream reading/writing, so it's basically useless for a cdn purpose.

**Comment by camjac251** [comment]
> 
> About the subdomain it would require significant changes at the xbackbone internal routing, and I don't see the point of doing that, as the file are accessed via the remote adapter.

BunnyCDN and BunnyCDN storage are two different use cases. Storage would be similar to S3 in that you have a bucket that you can store files in, but the CDN would mirror a domain, like cdn.website.com could go to storage.website.com, and then it would service the files through the lowest latency/closest server to the client and offer the best speeds.

This would solve any speed issues for large files buffering or any slow downs in routes as the CDN is able to do much better.

**Comment by camjac251** [comment]
If files go directly from S3 or Google Cloud to the client then sure a subdomain might not be needed. But if the files go through the server and the server serves these files through a connection to the server, then a subdomain for serving them would be very beneficial.

**Comment by camjac251** [comment]
I noticed that with S3, files are downloaded in full to the server before PHP serves them. Does the flysystem S3 filesystem not support streaming?

**Comment by camjac251** [comment]
Opening a new issue in case you don't see this reply

**Comment by SergiX44** [comment]
Already replied in the other issue, closing this one.
