### ISSUE TITLE
Add line counter in file viewer

### ISSUE THREAD

**Issue by Pe46dro** [SergiX44/XBackBone#214]
As in title and like discussed on Teamspeak, I'd like to see a line count on the text file viewer:

![image](https://user-images.githubusercontent.com/6197075/81510091-aa596800-930f-11ea-8200-013eed95d9b9.png)

**Comment by SergiX44** [comment]
Do you know something that works better than highlight.js?

**Comment by idblock** [comment]
prism.js ?

**Comment by SergiX44** [comment]
I've looked into that, but it doesn't support automatic language recognition on-the-fly. I'm looking into a plugin for highlight.js and and see how it goes.

**Comment by idblock** [comment]
Name of this plugin ?
