### ISSUE TITLE
S3 file streaming support

### ISSUE THREAD

**Issue by camjac251** [SergiX44/XBackBone#215]
In the current version of XBackBone, files are cached locally from S3 before uploaded or downloaded. This can be sometimes frustrating for larger files that take longer than the max php execution time set to download.

Would it be possible to implement file streaming through S3?
https://docs.aws.amazon.com/aws-sdk-php/v2/guide/feature-s3-stream-wrapper.html
https://github.com/thephpleague/flysystem-aws-s3-v3/issues/124

**Comment by SergiX44** [comment]
I can add the fix that you linked from the flysystem aws adapter, but it's not something really under my control. If after adding the configuration it's still not works as expected that issue should be opened in the upstream library.
