### ISSUE TITLE
xbackbone + nginx/reverse proxy -- 'Unable to connect'.  config problem or bug?

### ISSUE THREAD

**Issue by pgnd** [SergiX44/XBackBone#218]
( not entirely sure if this _is_ a bug on a supported usecase, a feature request or a support question ... pls re-tag as req'd )

i've installed xbackbone/git on linux

```
**System Info**
+ PHP Version:
	PHP 7.4.6-dev (cli) (built: Apr 12 2020 19:23:21) ( NTS )
	Copyright (c) The PHP Group
	Zend Engine v3.4.0, Copyright (c) Zend Technologies
	    with Zend OPcache v7.4.6-dev, Copyright (c), by Zend Technologies

+ XBackBone Version:
	git log -n1
	      1 commit 45cea0e794f55b09af5bda05b81d17bddca4badc (HEAD -> master, origin/master, origin/HEAD)
	      2 Merge: 1d0f5b1 18911de
	      3 Author: Sergio Brighenti <sergio@brighenti.me>
	      4 Date:   Thu May 14 13:41:17 2020 +0200
	      5
	      6     Merge pull request #216 from camjac251/master
	      7
	      8     Add S3 Endpoint Support

+ Webserver: [Apache/Nginx/...]
	nginx -v
		nginx version: nginx/1.18.0 (pgnd Build)

+ Database backend: [SQLite/Mysql/...]
	sqlite3 --version
		3.31.1 2020-01-27 19:55:54 3bfa9cc97da10598521b342961df8f5f68c7388fa117345eeb516eaa837balt1
```

Running as a standalone instance on Nginx, no issues.

I'm trying to mv it behind an Nginx frontend/reverse proxy.

The goal is

--	xbackbone exposed @ frontend subdir == https://example.com/share
--	xbackbone backend @ https://xbackbone.example.com/share

atm, config is quite similar to my usual/frequent proxy+backend setup

nginx frontend,
```
server {
	listen 10.0.0.1:443 ssl http2;
	server_name example.com;

	location /share/ {
		proxy_pass https://xbackbone.example.com:10000/;
		proxy_ssl_name xbackbone.example.com;
		proxy_ssl_certificate         "/srv/ssl/xbackbone/client.crt";
		proxy_ssl_certificate_key     "/srv/ssl/xbackbone/client.key";
		proxy_ssl_trusted_certificate "/srv/ssl/xbackbone/ca.crt";

        set_real_ip_from 10.0.0.0/24;
        real_ip_header X-Forwarded-For;
        real_ip_recursive on;

        proxy_set_header  X-Script-Name /share;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Uri $request_uri;
        proxy_set_header Accept-Encoding "";
        proxy_set_header Destination $http_destination;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header X-Remote-User $remote_user;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Ssl on;
        proxy_redirect  http://  $scheme://;
        proxy_set_header X-SSL-Subject $ssl_client_s_dn;
        proxy_set_header X-SSL-Issuer  $ssl_client_i_dn;
        proxy_set_header HTTPS on;
        proxy_ssl_session_reuse off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

	}
}
```

nginx backend,
```
server {
	listen 127.0.0.1:10000 ssl http2;

	server_name xbackbone.example.com;

	root /src/apps/xbackbone/;
	index index.php;
	include includes/ssl_protocol.inc;

	ssl_certificate        "/srv/ssl/xbackbone/server.crt";
	ssl_certificate_key    "/srv/ssl/xbackbone/server.key";

	autoindex off;
	index index.html index.htm index.php;
	charset utf-8;

	location /app         { return 403; }
	location /bin         { return 403; }
	location /bootstrap   { return 403; }
	location /resources   { return 403; }
	location /storage     { return 403; }
	location /vendor      { return 403; }
	location /logs        { return 403; }
	location CHANGELOG.md { return 403; }

	location / {
	        try_files $uri $uri/ /index.php?$query_string;
	}

	error_page 404 /index.php;
	location ~ \.php$ {
		fastcgi_pass   phpfpm;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
		fastcgi_param SCRIPT_NAME $fastcgi_script_name;
		include fastcgi_params;

		error_log /var/log/nginx/xbackbone.example.com.error.log info;
	}
}
```

xbackbone config,
```
<?php

return [
	'base_url' => 'https://example.com/share',
	'storage' => [
		'driver' => 'local',
		'path' => '/src/xbackbone',
	],
	'db' => [
		'connection' => 'sqlite',
		'dsn' => '/srv/db/xbackbone/xbackbone.db',
		'username' => null,
		'password' => null,
	]
];
```

with that^ config, a visit to

	https://example.com/share/

ends up redirecting to

	https://xbackbone.example.com:10000/home

displaying

	Unable to connect
	Firefox can’t establish a connection to the server at xbackbone.example.com:10000.

Nothing at all in the xbackup logs, so seems it's not getting that far.

In my nginx log, no error either
```
[16/May/2020:10:32:19 -0700] 127.0.0.1 - - - xbackbone.example.com  to: unix:/run/php-fpm.sock: GET / HTTP/1.1 upstream_response_time 0.004 msec 1589650339.137 request_time 0.004
[16/May/2020:10:32:19 -0700] 10.0.0.25 - - - example.com  to: 127.0.0.1:10000: GET /share/ HTTP/2.0 upstream_response_time 0.008 msec 1589650339.137 request_time 0.009
```

What/where config changes are needed to get to XBackBone UI through the frontend proxy?

**Comment by SergiX44** [comment]
I think it's a config problem. The base_url is what is actually used to build redirects and links. Also, if the page doesn't work even directly loading the page (in you example, going to the https://example.com/share/login) something is not working in your configuration.

**Comment by pgnd** [comment]
with nginx BACK-end config
```
server {
    listen 10.1.0.10:11111 ssl http2;
    server_name xbackbone.example.com;
    root /srv/apps/XBackBone/;
    index index.php;

    include includes/ssl_protocol.inc;

    ssl_certificate        "/etc/ssl/nginx/xbackbone.example.com.server.EC.crt.pem";
    ssl_certificate_key    "/etc/ssl/nginx/xbackbone.example.com.NOPASS.server.EC.key.pem";

    autoindex off;
    index index.html index.htm index.php;
    charset utf-8;

    location /app         { return 403; }
    location /bin         { return 403; }
    location /bootstrap   { return 403; }
    location /resources   { return 403; }
    location /storage     { return 403; }
    location /vendor      { return 403; }
    location /logs        { return 403; }
    location CHANGELOG.md { return 403; }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    error_page 404 /index.php;
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass   phpfpm;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        include fastcgi_params;
    }

}
```

seems to me that the "/share/" subdir should only be a front-end issue.  so mod'ing XBackBone config to,
```
/srv/apps/XBackBone/config.php
	<?php

	return [
	    'app_name' => 'Group /share',
	    'base_url' => 'https://xbackbone.example.com:11111',
	    'storage'  => [
	        'driver' => 'local',
	        'path'   => '/data/xbackbone',
	    ],
	    'db'       => [
	        'connection' => 'sqlite',
	        'dsn'        => '/data/db/xbackbone/xbackbone.db',
	        'username'   => null,
	        'password'   => null,
	    ]
	];
```

visit directly to

	https://xbackbone.example.com:11111

immediately redirects to

	https://xbackbone.example.com:11111/login

I _do_ see the expected login

	https://i.imgur.com/TaTC0hh.png

next, with nginx FRONT-end
```
server { # INTERNAL PRODUCTION LISTENER

    listen 10.1.0.10:443 ssl http2;
    server_name example.com;
	...
    location /share/ {

        proxy_pass https://xbackbone.example.com:11111/;
        proxy_ssl_name xbackbone.example.com;
        proxy_ssl_certificate         "/etc/ssl/nginx/xbackbone.example.com.client.crt";
        proxy_ssl_certificate_key     "/etc/ssl/nginx/xbackbone.example.com.client.key";
        proxy_ssl_trusted_certificate "/etc/ssl/nginx/ca.crt";

        set_real_ip_from 10.1.0.0/24;
        real_ip_header X-Forwarded-For;
        real_ip_recursive on;
        proxy_http_version 1.1;
        proxy_intercept_errors  on;
        proxy_redirect  http://  $scheme://;
        proxy_set_header Accept-Encoding ""; # Optimize encoding
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Destination $http_destination;
        proxy_set_header Host $http_host;
        proxy_set_header HTTPS on;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Ssl on;
        proxy_set_header X-Forwarded-Uri $request_uri;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Remote-User $remote_user;
        proxy_set_header X-Script-Name /share;
        proxy_set_header X-SSL-Issuer  $ssl_client_i_dn;
        proxy_set_header X-SSL-Subject $ssl_client_s_dn;
        proxy_ssl_session_reuse off;
    }
```

nav to

	https://example.com/share/

immediately redirects, incorrectly, to

	https://example.com:11111/

causing an SSL cert mismatch error

BUT ...
nav _directly_ to the LOGIN @

	https://example.com/share/login

DOES correctly display the login.

	https://i.imgur.com/TaTC0hh.png


The problem, atm, is -- with my current config -- visit to

	https://example.com/share/

fails to redirect to the

	https://example.com/share/login

so, back to "something is not working in your configuration."

the question is -- what?

**Comment by pgnd** [comment]
also

if I nav to the front-end login URL

	https://example.com/share/login

and enter credentials + submit, i'm redirected to

	https://xbackbone.example.com:11111/home

where, I'm authenticated and see the XBackBone portal UI

functional, but displayed at the 'wrong' internal/backend URI.

clearly an issue somewhere with redriect/rewrite between the front- and back-ends.

**Comment by SergiX44** [comment]
The base_url should be set at the url you want. If the you want it on the `https://example.com/share/`, the base url will be `https://example.com/share`.
You can also try removing the base_url from the config, and the base_url will be extracted from the incoming request.

**Comment by pgnd** [comment]
@SergiX44 

hi,

> if the you want it on the https://example.com/share/, the base url will be https://example.com/share and not https://xbackbone.example.com:11111.

changing
```
config.php
-	'base_url' => 'https://xbackbone.example.com:11111',
+	'base_url' => 'https://example.com/share',
```

*does*, as you suggest, fix the displayed URI.

so, nav to 

	https://example.com/share/login

displays the XBackBone login, and after submit, redirects to

	https://example.com/share/home

all links within the UI, behind the reverse proxy,

	https://example.com/share/XXX

now work as expected. +1 !

But the parent still is a problem. Nav to

	https://example.com/share

still incorrectly redirects to

	https://example.com:11111

**Comment by pgnd** [comment]
> That I think that is a nginx config issue,

ok, I'll poke at nginx config.

something's odd here ... my front end config is basically the same for all my backends, with the occassional add'l header as required by any particular backend.

so either I'm missing an obvious mistake in my config (possible! checking ...), or there's something unique to this backend.

**Comment by SergiX44** [comment]
Another thing that can help, every trailing slash url is redirected to the non-trailing counter part by default (example https://example.com/share/login/ is redirected by the framework to https://example.com/share/login):
https://github.com/SergiX44/XBackBone/blob/master/bootstrap/app.php#L88
The redirect is based on the request uri, so, again, should something that is set by the proxy in your case.

**Comment by SergiX44** [comment]
For testing, you can comment out this block: https://github.com/SergiX44/XBackBone/blob/master/bootstrap/app.php#L88-L107

**Comment by pgnd** [comment]
commented out the block, didn't see any change in behavior.

navs to EITHER

  https://example.com/share
  https://example.com/share/

still end up at

  https://example.com:11111

as above.

i supsect you're right -- that it's the proxy setup.

just a matter of figuring out -- what.

**Comment by hitnrun30** [comment]
I just keep getting "No input file specified."  no matter what  But it does go to the right page.

nginx.conf

location / { 
			try_files $uri $uri/ /index.php?$query_string;
		}
		
		location ~ \.php$ {
            fastcgi_pass   127.0.0.1:9000;
			fastcgi_index  index.php;
            proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			fastcgi_split_path_info ^(.+\.php)(/.+)$;
			fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
			fastcgi_param SCRIPT_NAME $fastcgi_script_name;
			include fastcgi_params;
        }

**Comment by pgnd** [comment]
heh, and no matter what, here, it doesn't!

atm,

https://kandr.net/share/login  takes me, correctly, to the login
https://kandr.net/share/login/  returns '404 Not Found'
https://kandr.net/share/ redirects to https://example.com:11111

As an experiment, I dropped in 'fat' nextcloud into a similar setup.  Works perfectly.

Yeah, I know it's *something* in my config ... at least.  So far, no clue :-/

**Comment by SergiX44** [comment]
I don't know what's wrong, I've never used nginx for this type of configuration, I invoke @Pe46dro.

**Comment by hitnrun30** [comment]
Same here, the reverse proxy is not very forgiving.

**Comment by hitnrun30** [comment]
Anything on this

**Comment by gramakri** [comment]
I hit this issue when trying to make a Cloudron package for XBackBone. On Cloudron, we have a nginx reverse proxy at the front and use apache at the back (very similar setup to this report). The apache at the back runs on port 8000. XBackBone will redirect to `https://app.com:8000` . This is despite setting base_url to `https://app.com` .

I investigated this a bit and the root cause is that `request->getUri` does not understand the reverse proxy variables. For example, in https://github.com/SergiX44/XBackBone/blob/90062a668d2db34a7c60badc05f149d4f4b9db07/app/Middleware/AuthMiddleware.php#L21 , the `redirectTo` is set in the session to the URI and we will get redirected there.

I can't link to the code here since the function comes from vendor/ . getUri() relies on HTTP_HOST variable and this messes things up (which is the root cause).

**Comment by gramakri** [comment]
https://github.com/guzzle/psr7/issues/130#issuecomment-373259208 and https://github.com/guzzle/psr7/issues/189 are the upstream issues (which are unfortunately closed with no resolution).

For Cloudron package, we can workaround this by simply running apache on port 80.
