### ISSUE TITLE
Uploading on Share X redirects to login page

### ISSUE THREAD

**Issue by enescaglayan** [SergiX44/XBackBone#223]
**System Info**
+ PHP Version: 7.3.6
+ XBackBone Version: 3.1.4
+ Webserver: [Apache/Nginx/...] cpanel
+ Database backend: [SQLite/Mysql/...] sqlite

**Describe the bug**
When I try to upload something it redirects sharex to vault/login instead of giving a json response or whatever with the urls

**To Reproduce**
1. get the sharex configuration file
2. open the file and set the default custom uploaders to it
3. click test

**Expected behavior**
A response with my uploaded file

**Screenshots**
![image](https://user-images.githubusercontent.com/47847977/82907452-4f5e7c80-9f6f-11ea-916d-d78b468adccb.png)
![image](https://user-images.githubusercontent.com/47847977/82907475-571e2100-9f6f-11ea-8c14-d8f38d16e7e7.png)
![image](https://user-images.githubusercontent.com/47847977/82907501-5eddc580-9f6f-11ea-9431-73515ec61fab.png)

**Comment by SergiX44** [comment]
In the link you have provided, the upload url is not working.

```
$ curl -X POST https://enescaglayan.ml/vault/upload
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Your nginx configuration is probably wrong. https://github.com/SergiX44/XBackBone/blob/master/nginx.conf

**Comment by enescaglayan** [comment]
How do i fix it? In filezilla i dont see any nginx.conf file

**Comment by SergiX44** [comment]
Should not be uploaded. Those directives must be added to your nginx config.

**Comment by enescaglayan** [comment]
Okay, thanks
