### ISSUE TITLE
Discord preview support

### ISSUE THREAD

**Issue by crysis992** [SergiX44/XBackBone#227]
**Is your feature request related to a problem? Please describe.**
I'm not sure if it is a configuration error of my webserver (using nginx) or if it's something you need to add.
I'm using ShareX to get a direct link directly into my clipboard after a upload was successfull and I noticed that discord doesnt seem to display a preview image.

**Describe the solution you'd like**
Would be ideal if discord would display the image after posting the link.

**Additional context**
Here is a screenshot:
First link is the link I got from ShareX into my clipboard
Second link is the raw link I got from XBackBone
Third link is a link from my old image host that I've used before.

![preview_discord_bug](https://user-images.githubusercontent.com/5308174/83806403-bdaee780-a6b1-11ea-8835-2506f70555d2.png)

**Comment by yuvali1337** [comment]
Hi i can assure you this is no xBackBone issue, I use it with Apache and discord previews work completely fine. If you're using cloudflare make sure its not blocking discordbot, if not recheck your Nginx config.
<img src=https://img.shibe.host/DIFu4/pEqaMiyE50.png/raw></img>

**Comment by SergiX44** [comment]
If xbackbone receive a request from "bots" (discord, telegram, facebook, etc) the raw file is automatically served. As pointed out @yuvali1337, if is not working something on your end is blocking the requests from those bots.
