### ISSUE TITLE
doesnt show picture

### ISSUE THREAD

**Issue by Benjjiyy** [SergiX44/XBackBone#234]
when i take a screenshot and send it to someone it doesnt show up
heres a screenshot i took:
http://www.nosocial.life/leFu5/pIYODoqi99.png

**Comment by yuvali1337** [comment]
Try adding /raw at the end

**Comment by Benjjiyy** [comment]
http://www.nosocial.life/leFu5/pIYODoqi99.png/raw

**Comment by SergiX44** [comment]
The links are not working.
Please follow the bug report template. The info you gived here are basically useless.

**Comment by Benjjiyy** [comment]
> The links are not working.
> Please follow the bug report template. The info you gived here are basically useless.

yeah i guess, i made a new named "screenshot" sry for the inconvenience.
