### ISSUE TITLE
Ability to disable plyr.io

### ISSUE THREAD

**Issue by gerroon** [SergiX44/XBackBone#236]
Hi,

I am not sure when the ply.io was integrated but I find it to be super buggy at least on Linux Firefox. I am wondering if there is a way to disable it and the browser deal with it when it is possible?

thanks

**Comment by SergiX44** [comment]
What kind of problems are you experiencing?
There is not a "right" way to disable it, but deleting/renaming the plyr folder in static/ folder should do the trick.

**Comment by gerroon** [comment]
Hi

It does not play the videos at all, at least from my instance on Firefox 76.  Scrubbing works but pressing play does nothing with .mp4 which is my togo video format. This was not an issue when it was the native player I believe.

**Comment by SergiX44** [comment]
When removing plyr the playback is working? It seems a strage issue

**Comment by SergiX44** [comment]
You should look upstream in the plyr.io repo and try to open there an issue if it's specific to Firefox/Linux. I wasn't able to reproduce the issue on windows, and my linux laptop is currently broken. 

Closing for now, feel free to reopen if you have more infos.
