### ISSUE TITLE
Slack friendly URL?

### ISSUE THREAD

**Issue by gerroon** [SergiX44/XBackBone#238]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Is it possible to make the links Slack friendly so that the links show up as previews in the channel? Slack seems to be able to generate previews for other sites but not for my XBackBone instance urls.

**Additional context**
Url preview works fine in Riot.

thanks

**Comment by SergiX44** [comment]
Can you post the web server access logs where the slack bot is requesting an url? Some Slack bots was already added, but maybe they've changed it in the mean time.

**Comment by gerroon** [comment]
I do not see anything about slack bots in Apache config or in XBBone logs. Do you know how to get what are looking for here?

**Comment by gerroon** [comment]
Ok found couple lines

```
"GET /files/xxxx/xxxxxx.jpg HTTP/1.1" 200 98371 "-" "Slackbot-LinkExpanding 1.0 (+https://api.slack.com/robots)"
"GET /files/xxxx/xxxxxx.jpg HTTP/1.1" 200 98371 "-" "Slackbot 1.0 (+https://api.slack.com/robots)"
 "GET /files/xxxx/xxxxxx.jpg HTTP/1.1" 200 98371 "-" "Slack-ImgProxy (+https://api.slack.com/robots)"
 "GET /files/xxxx/xxxxxx.jpg HTTP/1.1" 200 98371 "-" "Slack-ImgProxy (+https://api.slack.com/robots)"

```

**Comment by yuvali1337** [comment]
Can you also add the Steam Chat bot
Valve/Steam HTTP Client 1.0
