### ISSUE TITLE
[Question] Self Hosting

### ISSUE THREAD

**Issue by matrix2113** [SergiX44/XBackBone#239]
Hey there, is it possible to self host this repo on my own domain using Cpanel? If so, would it be similar to the default one or is there a different step by step?

Thanks

**Comment by yuvali1337** [comment]
Yes you can. Install the missing php extensions on the cPanel, and upload the files trough the file manager/ftp

**Comment by matrix2113** [comment]
@yuvali1337 are you referring the missing php extensions [here](https://sergix44.github.io/XBackBone/installation.html#prerequisites)?

**Comment by yuvali1337** [comment]
Yes, you also need to change your php version as usually it comes in 5.x

**Comment by matrix2113** [comment]
gotcha, thank you! 👍
