### ISSUE TITLE
The requested URL /xbackbone/home was not found on this server.

### ISSUE THREAD

**Issue by OdinGitDat** [SergiX44/XBackBone#24]
**System Info**
+ PHP Version: 7.2.15-0ubuntu0.18.10.1
+ XBackBone Version: 2.5
+ Webserver: Apache/2.4.34 (Ubuntu)

**Describe the bug**
"The requested URL /xbackbone/home was not found on this server." After finishing web installation.

Config file:
```
<?php
return array (
  'base_url' => 'https://xxxxx',
  'storage_dir' => 'storage',
  'db' => 
  array (
    'connection' => 'mysql',
    'dsn' => 'host=localhost;port=3306;dbname=xbackbone',
    'username' => 'xbackbone',
    'password' => 'xxxxx',
  ),
);
```

**Comment by SergiX44** [comment]
Have you enabled the mod_rewrite on the apache server?
It's installed in the subdirectory /xbackbone/ ?

**Comment by SergiX44** [comment]
Please check that htaccess file and mod rewrite is actually enabled on your system, and file permissions are set correctly.

**Comment by OdinGitDat** [comment]
` a2enmod rewrite` returns `Module rewrite already enabled` and I have set `chmod -R 777 /var/www/xbackbone`. Still get the same result.

I don't know what else I can do.

**Comment by SergiX44** [comment]
Check that the base url in the config its correct, and also check the file .htaccess is loaded by apache.

**Comment by OdinGitDat** [comment]
I have verified both the htaccess and config file and it does not change anything. Is there anything else xbackbone relies on?

If it helps to know, I can interact with some/most href on the page, but no js or css is loaded.

**Comment by JonathanJhon55** [comment]
I am also facing the same issue. Tried everything you said @SergiX44 the issue still persists

**Comment by SergiX44** [comment]
> I am also facing the same issue. Tried everything you said @SergiX44 the issue still persists

> If it helps to know, I can interact with some/most href on the page, but no js or css is loaded.

Can you post the Apache error.log?


> If it helps to know, I can interact with some/most href on the page, but no js or css is loaded.

All the css/js assets are in the default `/static` folder, please check that this folder is readable and accessible by the web server.

**Comment by JonathanJhon55** [comment]
> > I am also facing the same issue. Tried everything you said @SergiX44 the issue still persists
> 
> > If it helps to know, I can interact with some/most href on the page, but no js or css is loaded.
> 
> Can you post the Apache error.log?
> 
> > If it helps to know, I can interact with some/most href on the page, but no js or css is loaded.
> 
> All the css/js assets are in the default `/static` folder, please check that this folder is readable and accessible by the web server.

[Fri Mar 29 17:02:31.792912 2019] [mpm_event:notice] [pid 13784:tid 139815335839616] AH00489: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Fri Mar 29 17:02:31.793095 2019] [core:notice] [pid 13784:tid 139815335839616] AH00094: Command line: '/usr/sbin/apache2'
[Fri Mar 29 17:04:40.191434 2019] [mpm_event:notice] [pid 13784:tid 139815335839616] AH00491: caught SIGTERM, shutting down
[Fri Mar 29 17:04:41.347655 2019] [mpm_prefork:notice] [pid 22167] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Fri Mar 29 17:04:41.348655 2019] [core:notice] [pid 22167] AH00094: Command line: '/usr/sbin/apache2'
[Fri Mar 29 17:04:42.934295 2019] [mpm_prefork:notice] [pid 22167] AH00169: caught SIGTERM, shutting down
[Fri Mar 29 17:04:43.151105 2019] [mpm_prefork:notice] [pid 22269] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Fri Mar 29 17:04:43.151205 2019] [core:notice] [pid 22269] AH00094: Command line: '/usr/sbin/apache2'
[Fri Mar 29 17:06:50.575698 2019] [mpm_prefork:notice] [pid 22269] AH00169: caught SIGTERM, shutting down
[Fri Mar 29 17:06:51.776099 2019] [mpm_prefork:notice] [pid 27048] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Fri Mar 29 17:06:51.776205 2019] [core:notice] [pid 27048] AH00094: Command line: '/usr/sbin/apache2'
[Fri Mar 29 17:09:44.549249 2019] [mpm_prefork:notice] [pid 27048] AH00169: caught SIGTERM, shutting down
[Fri Mar 29 17:09:45.773598 2019] [mpm_prefork:notice] [pid 27181] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Fri Mar 29 17:09:45.773699 2019] [core:notice] [pid 27181] AH00094: Command line: '/usr/sbin/apache2'

These are my logs when I go onto the URL, however when I remove /home (which it automatically goes to) and I do /index.php I get the login page

**Comment by OdinGitDat** [comment]
I found the problem on my side. I checked the apache error log, there were no xbackbone related errors. But when I checked the access.log I noticed that all the assets were returning a 404 because it's looking in the wrong folder. Below is a redacted log (xxx.xxx is my domain).
````
[29/Mar/2019:17:44:25 +0100] "GET /xbackbone/ HTTP/1.1" 302 3297 "-" "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0"
[29/Mar/2019:17:44:25 +0100] "GET /xbackbone/home HTTP/1.1" 200 1990 "-" "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0"
[29/Mar/2019:17:44:25 +0100] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 404 457 "https://xxx.xxx/xbackbone/home" "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0"
[29/Mar/2019:17:44:25 +0100] "GET /static/jquery/jquery.min.js HTTP/1.1" 404 446 "https://xxx.xxx/xbackbone/home" "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0"
````
As you can see the home folder is correctly GET from _/xbackbone/home_. But the static folder is GET from _/static/_ instead of _/xbackbone/static_!

So when I change the base url in the config to _https://xxx.xxx/xbackbone_ **instead** of _https://xxx.xxx_ it works. 

But now all the href in the page link to e.g. _https://xxx.xxx/xbackbone/xbackbone/users_. Also _https://xxx.xxx/xbackbone_ redirects to _https://xxx.xxx/xbackbone/xbackbone/home_ now.

I don't know why this is happening but I'm sure you know given this info.

**Comment by SergiX44** [comment]
> I found the problem on my side. I checked the apache error log, there were no xbackbone related errors. But when I checked the access.log I noticed that all the assets were returning a 404 because it's looking in the wrong folder. Below is a redacted log (xxx.xxx is my domain).
> 
> ```
> [29/Mar/2019:17:44:25 +0100] "GET /xbackbone/ HTTP/1.1" 302 3297 "-" "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0"
> [29/Mar/2019:17:44:25 +0100] "GET /xbackbone/home HTTP/1.1" 200 1990 "-" "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0"
> [29/Mar/2019:17:44:25 +0100] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 404 457 "https://xxx.xxx/xbackbone/home" "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0"
> [29/Mar/2019:17:44:25 +0100] "GET /static/jquery/jquery.min.js HTTP/1.1" 404 446 "https://xxx.xxx/xbackbone/home" "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0"
> ```
> As you can see the home folder is correctly GET from _/xbackbone/home_. But the static folder is GET from _/static/_ instead of _/xbackbone/static_!
> 
> So when I change the base url in the config to _https://xxx.xxx/xbackbone_ **instead** of _https://xxx.xxx_ it works.
> 
> But now all the href in the page link to e.g. _https://xxx.xxx/xbackbone/xbackbone/users_. Also _https://xxx.xxx/xbackbone_ redirects to _https://xxx.xxx/xbackbone/xbackbone/home_ now.
> 
> I don't know why this is happening but I'm sure you know given this info.

Assuming that your document root is `/var/www/`, and you have xbackbone installed in the `/xyz` sub folder (abs: `/var/www/xyz/`), the `base_url` to be inserted in the config file will be accordingly `https://xxx.xxx/xyz` (no trailing slash).

I'm not sure how [this](https://github.com/SergiX44/XBackBone/issues/24#issuecomment-472426906) could influence the apache because I don't know if you have other directives in your apache.conf, but if it's generally configured to `AllowOverride All`, it should get the xbackbone's .htaccess without issues.

Can you try the installation from scratch, checking that apache is configured to read the correct folders?

**Comment by OdinGitDat** [comment]
> Assuming that your document root is `/var/www/`, and you have xbackbone installed in the `/xyz` sub folder (abs: `/var/www/xyz/`), the `base_url` to be inserted in the config file will be accordingly `https://xxx.xxx/xyz` (no trailing slash).

This was not at all apparent from the installation guide and may have been the source of this entire issue. I will try a complete reinstall knowing this and report back here.

**Comment by SergiX44** [comment]
Closed for inactivity. Feel free to reopen this issue if needed.

**Comment by gerroon** [comment]
I have this issue still and setting it with the full path does not help.

Here
`'base_url' => 'https://DOMAIN/sharex`

Sends me to 
https://DOMAIN/sharex/sharex/home

Anything else I could try?  I have apll the apache stuff installed and set properly
