### ISSUE TITLE
Previews not showing up

### ISSUE THREAD

**Issue by Lisalhol** [SergiX44/XBackBone#242]
Apologies I'm relatively new to this. I've checked issues, googled and read documentation

I've installed it all okay (via the web install) I have all the pre-req. I've thoroughly read the documentation. Everything is working but the previews. I checked that the php-gd is installed. 
What should my next check be. I've got Chev installed on a subdomain and the previews are working there so I'm wondering what I've missed?

Thank you for the work you've done for this!

![DaheFAhO65](https://user-images.githubusercontent.com/62408164/88581739-891e3300-d045-11ea-8ac1-7e3017066cae.png)

**Comment by SergiX44** [comment]
Can you post the logs from xbackbone and the web server?
