### ISSUE TITLE
Storage and URL Question

### ISSUE THREAD

**Issue by DevilDonkey69** [SergiX44/XBackBone#244]
Hello there,

I am basically wondering if it is possible to change the name of the folder that the images upload to within the storage file.
Currently it is set to `GEYe8` and stays as that if I try to rename the folder.
Also is there a way to shorten the URL or move the storage location safely to lets say the main directory.
Ex: www.website.net/screenshots/<image.png>
Instead of it being: www.website.net/screenshots/GEYe8/<image.png>

**Comment by SergiX44** [comment]
No, you can't change how currently the file are stored.
Since it's meant to be multi-user every user has it's personal space to have unique urls.
