### ISSUE TITLE
No previews (discord ect.)

### ISSUE THREAD

**Issue by StephanBruh** [SergiX44/XBackBone#253]
Previews aren't working on discord and when I do a meta tags check.
I'm running on Nginx, I can see in the access logs thats it accessing the page and the correct url. Nothing more. Nothing in the error logs. Nothing special in the xbackbone logs,

Somebody any ideas? 

testlink: https://i.stephanbruh.nl/wEpi0/WaVisoda65.jpg

**Comment by StephanBruh** [comment]
Fixed

**Comment by ravicant** [comment]
> Fixed, changed some cloudflare settings.

can u help me with it

**Comment by Pe46dro** [comment]
Check [here](https://xbackbone.app/common_issues.html#discord-telegram--is-not-showing-the-imagevideo-preview-of-the-link)

**Comment by Repooc** [comment]
> Fixed, changed some cloudflare settings.

Can you tell me what you changed as I recall not having issues with a video embedding until recently but don't think I changed any cloudflare settings.  I saw the link Pe46dro linked but it doesn't really show/describe the actual setting they are referring to.
