### ISSUE TITLE
Remove Telegram share button

### ISSUE THREAD

**Issue by mihha** [SergiX44/XBackBone#254]
Hi guys,

this is not so much a feature request, but more a search for help

I am trying to remove "Telegram share" button on the frontend but so far haven't been able to find a solution

Can you please guide me into the right direction? I am sure that an easy solution exists but I just couldn't find it yet

I have changed the cache file in the following folder
./resources/cache/twig/

but now, my frontend shows the following issue 
![image](https://user-images.githubusercontent.com/3791124/91696025-47fece80-eb6f-11ea-92f3-053849cadc6b.png)

How can I recreate cache file and bring back the default functionality if Telegram button removal can't be done?

Thank you all in advance!

**Comment by mihha** [comment]
Hi,

OK. Just to answer my own question (I found this just after I hit submit here)

Edit file 
./resources/templates/upload/public.twig

and remove telegram button code from there

Remove file from the cache and visit the resource page again so the new cache file can be generated

It would be nice feature if you could add this kind of possibility in the System settings but for now, this works for me

Thank you!

**Comment by SergiX44** [comment]
I'll probably drop this button at some point since it's pretty useless.
