### ISSUE TITLE
Clear Site Cache Button

### ISSUE THREAD

**Issue by yuvali1337** [SergiX44/XBackBone#256]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
A button to clear site the cache of the system, i'd like to have a button in the system to clear the cache of the sites because sometimes people edit the src and can't figure out why it doesn't update, a clear cache button would be nice i guess peepoSmile

**Comment by SergiX44** [comment]
It's already a command, you can find it in `bin/clean`.
Should no be triggered while you are on the website, because it drop sessions, twig files, and other temps file. So I don't think it's a good idea having it on the dashboard itself.
