### ISSUE TITLE
use more than one domain

### ISSUE THREAD

**Issue by iphqne** [SergiX44/XBackBone#257]
i have 3 domains linked to my website but if i change the upload site it always returns the base url in config.php and i wanna know how to make it so the return image url uses the domain chosen in the URL part of the config
![image](https://user-images.githubusercontent.com/45533114/93019204-7d72d580-f5cd-11ea-87f6-ce569b3ad455.png)

**Comment by SergiX44** [comment]
Try to put the base url to `null`

**Comment by iphqne** [comment]
> Try to put the base url to `null`

returned this "/zaKO9/zEVuCAna08.png" so it returns everything except the url

**Comment by Pe46dro** [comment]
Try with `'http://'.$_SERVER['HTTP_HOST'];`

**Comment by SergiX44** [comment]
My bad, remove base url key from the config entirely

**Comment by iphqne** [comment]
> My bad, remove base url key from the config entirely

that worked, thank you

**Comment by bacitoto** [comment]
Is there a neater way to do this?
This does indeed work but ruins the copy url function
from 

example.com/sAkA0/nUhAMadI24.png
to
/sAkA0/nUhAMadI24.png
