### ISSUE TITLE
Complete translation ru.lang.php

### ISSUE THREAD

**Issue by webarion** [SergiX44/XBackBone#261]
Hi! I provide a complete translation file ru.lang.php for version 3.2.0.

[ru.lang.zip](https://github.com/SergiX44/XBackBone/files/5275039/ru.lang.zip)

**Comment by SergiX44** [comment]
Hi,
you should add the language string from weblate. The translations files are not modified via git.
https://hosted.weblate.org/projects/xbackbone/xbackbone/
