### ISSUE TITLE
Cant upload after update 3.20

### ISSUE THREAD

**Issue by StephanBruh** [SergiX44/XBackBone#265]
While testing it with the sharex test tool I get this in return

![image](https://user-images.githubusercontent.com/19285400/94349538-7aec9300-0045-11eb-82a3-0b69b9563563.png)

**Comment by SergiX44** [comment]
Check in the config.php, if there is a `maintenance => true`. This should not happen, please check file permissions.

**Comment by StephanBruh** [comment]
> Check in the config.php, if there is a `maintenance => true`. This should not happen, please check file permissions.

Thanks added that now into the config!
