### ISSUE TITLE
Where to find meta data? Embeded image

### ISSUE THREAD

**Issue by SevenT99** [SergiX44/XBackBone#269]
Since discord updated the link and media thing there will be no link shown.
Could you tell me where you defined the meta data?
Or could you add `<meta name="og:image" itemprop="image" content="path/to/image.png">`
The other things i can make on the settings page and works for main site, but not for images
I want to get a embeded message like that on lightshot

**Comment by Pe46dro** [comment]
Fixed in #273
We need to wait for @SergiX44 to merge and release a new version

**Comment by SevenT99** [comment]
Thanks that you added that. But in Discord it doesn't load the embeded version. It only loads the picture
