### ISSUE TITLE
Issue with Theme Loading

### ISSUE THREAD

**Issue by CookieCr2nk** [SergiX44/XBackBone#27]
**System Info**
+ PHP Version: PHP Version 7.3.3
+ XBackBone Version: XBackBone v2.5
+ Webserver: Apache2

**Describe the bug**
A clear and concise description of what the bug is:

I have an Issue with my xBackbone Version, the theme can't be change. When i will change the Theme it come  this Error: "
500 Internal Server Error

Unexpected error while handling the request.
".

**To Reproduce**
1. Go to 'https://example.com/system'
2. Click on 'Theme -> Choose one theme -> Apply'

**Expected behavior**

I have no idea. But when you need some logs, for example Error.log of the vHost i can give it to you.

**Screenshots**

500 Internal Server Error: https://cdn.noajoder.ch/4b967/5cab9c2290cbd.png

**Comment by SergiX44** [comment]
Can you post the error.log and the logs in the /logs folder of xbackbone?

**Comment by CookieCr2nk** [comment]
xBackbone Log Error: https://hastebin.com/mosiceduqo.cs

Error.Log : I can't find errors, that have a context with the Error.

**Comment by CookieCr2nk** [comment]
Okey, i have found out, that with the CLI i can change the theme successfully, but it won't work in the webinterface.

**Comment by SergiX44** [comment]
Fixed in future 2.5.1 bugfix release.
