### ISSUE TITLE
Custom uploader - Support mac uPic

### ISSUE THREAD

**Issue by matrix2113** [SergiX44/XBackBone#278]
This isn't really a bug but I wanted to know how I could use my custom uploader for Mac as ShareX isn't supposed yet.

**Comment by SergiX44** [comment]
Is not really strightforward, you need a client that supports custom uploaders, and then integrate it to generate it via XBackBone. Do you have clients to suggest?

**Comment by matrix2113** [comment]
Apologizes for the late response. I'm currently using uPic for Mac. My one problem is wondering what the fields `File field` and `Url Path` would be.

Attached is the [image](https://user-images.githubusercontent.com/49132750/96068259-917a5300-0e69-11eb-923f-e2bdc6fe53cb.png).

Thanks

**Comment by matrix2113** [comment]
Hey there. I have done some research. There are numerous apps that you can use with XBackBone but for example with uPic. (https://cdn.matax.dev/vawA7/vElAdUNI98.png).

**Comment by SergiX44** [comment]
How did you make it work? I saw that unfortunately it doesn't support "precompiled" configs like sharex. Can you write the steps below? So I can include them in the documentation for future mac users 😄

**Comment by matrix2113** [comment]
I provided it in the edit above.

**Comment by SergiX44** [comment]
Documentation updated.

**Comment by matrix2113** [comment]
Glad to help.
