### ISSUE TITLE
Broken on Docker

### ISSUE THREAD

**Issue by Ryonez** [SergiX44/XBackBone#28]
**System Info**
Latest docker image

**Describe the bug**
xbackbone works fine until the docker is stopped. After it's stopped, it never comes back up.

**To Reproduce**
1. Install docker image
2. Run it
3. Stop it
4. start it

**Expected behavior**
To start up again

**Screenshots**
From the log:
![image](https://user-images.githubusercontent.com/16157130/56175156-f329e900-6049-11e9-9ce4-18b2d672ad18.png)

**Comment by SergiX44** [comment]
I'm not the maintainer of the docker image with xbackbone I'm sorry. You should open the issue con the Pedro's repo. @Pe46dro
https://github.com/Pe46dro/XBackBone-docker

**Comment by Ryonez** [comment]
Oh my mistake, sorry for that.
