### ISSUE TITLE
https ??

### ISSUE THREAD

**Issue by asdassdjn** [SergiX44/XBackBone#295]
how to make it https ?? after it's already HTTP?

**Comment by asdassdjn** [comment]
Basically I installed it using http made cloud flare connect to website but xbackbone is still using http

**Comment by asdassdjn** [comment]
Also on top of that my website is like example.com/xbackbone/login how do. I make it just example.com

**Comment by SadFarm1** [comment]
You need to use a reverse proxy in combination with Cloudflare. See [nginx](https://www.nginx.com/)

**Comment by asdassdjn** [comment]
I ended up figuring it out I guess. I got https I set it up with cloudlfare and got the private key form them and pasted it in some config file cant really remember. Where can I manually edit my tag code? like the user code for example ba9x0

**Comment by yuv41** [comment]
Did you make sure your base url is HTTPS?

**Comment by asdassdjn** [comment]
yeah it is

**Comment by SadFarm1** [comment]
You can use cloud flare certs if you'd like, I like using certbot. It's just personal preference

**Comment by SergiX44** [comment]
This is not really related to the application, but how you setup the webserver. Put the `https://..`in the config and enable full encryption if you are using cloudflare, or certbot as described earlier.
