### ISSUE TITLE
	User Code

### ISSUE THREAD

**Issue by asdassdjn** [SergiX44/XBackBone#297]
how do you change user code

**Comment by rossiscool123** [comment]
@asdassdjn 
You can edit the user code for a specific user using any database manager like PHPMyAdmin or Navicat which is how I do it. Go into the user's table and you should be able to see the user_code section which you can change. By default, the user_code has a 5 character limit which you can remove by increasing the varchar length.

**Comment by SergiX44** [comment]
Changing the schema is not raccomanded at all, this can cause truncated data in other columns in the future.
