### ISSUE TITLE
Mail, subject and accented characters

### ISSUE THREAD

**Issue by philippe317** [SergiX44/XBackBone#302]
**System Info**
+ PHP Version: 7.3.20
+ XBackBone Version: 3.3.3
+ Webserver: Apache
+ Database backend: Mysql/

**Describe the bug**
Hello, 

I noticed that when the application sends an email, the subject does not support accented characters (éàè)

See the image below ("création d'un nouveau compte")

![Capture](https://user-images.githubusercontent.com/18035521/102624662-9c40b500-4144-11eb-9242-f56db865d99c.PNG)

The problem is not present in the e-mail message.

I think I should change some parameters of mail(), if I believe a similar subject:

https://forums.commentcamarche.net/forum/affich-7033714-mail-php-probleme-d-accent-dans-sujet

$subject = utf8_decode($subject);
$subject = mb_encode_mimeheader($subject, "UTF-8");

**Comment by SergiX44** [comment]
Fixed.
