### ISSUE TITLE
Footer links and Mail formulars

### ISSUE THREAD

**Issue by XiNaru** [SergiX44/XBackBone#305]
Good day,

I just installed that and the whole time I'm looking for the file in which I don't add any more footer links. No, don't worry, the copyright line stays there. I'm interested in additional links such as Impressum and Datenschutz (sry i don't know what the two words are in english.)

next I look for the files in which I can edit and set up the mail form (activation email and password reset).

Hope you can help me. Thanks in advance.

**Comment by SergiX44** [comment]
The footer is located in this file: https://github.com/SergiX44/XBackBone/blob/master/resources/templates/base.twig
The registration things are located here: https://github.com/SergiX44/XBackBone/tree/master/resources/templates/auth

be sure to empty the `resources/cache` folder after editing any template, or call the script `bin/clean`
