### ISSUE TITLE
PHP7.4 Bug

### ISSUE THREAD

**Issue by DjSni** [SergiX44/XBackBone#307]
**System Info**
+ PHP Version: 7.4.14-1+ubuntu18.04.1+deb.sury.org+1
+ XBackBone Version: 3.3.3
+ Webserver: Apache
+ Database backend: Mysql

**Describe the bug**
Can no longer access the page due to the error and get an error 500 in the browser.
This error only occurs under PHP7.4, under 7.2 and 8.0 it works as usual.

**Expected behavior**
A normal call of the page

**Logs**
[Sun Jan 17 10:42:18.481013 2021] [php7:error] [pid 23670] [client IP:PORT] PHP Fatal error:  Uncaught Error: Call to undefined function App\\Web\\locale_accept_from_http() in /PATH/app/Web/Lang.php:61\nStack trace:\n#0 /PATH/resources/cache/di/CompiledContainer.php(87): App\\Web\\Lang::recognize()\n#1 [internal function]: CompiledContainer::{closure}()\n#2 /PATH/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array()\n#3 /PATH/vendor/php-di/php-di/src/CompiledContainer.php(116): Invoker\\Invoker->call()\n#4 /PATH/resources/cache/di/CompiledContainer.php(88): DI\\CompiledContainer->resolveFactory()\n#5 /PATH/vendor/php-di/php-di/src/CompiledContainer.php(53): CompiledContainer->get7()\n#6 /PATH/resources/cache/di/CompiledContainer.php(93): DI\\CompiledContainer->get()\n#7 /PATH/vendor/php-di/php-di/src/CompiledContainer.php(53): CompiledContainer->get8()\n#8 /PATH/app/Factories/ViewFactory.php(31): DI\\CompiledContainer->get()\n#9 /PATH in /PATH/app/Web/Lang.php on line 61

**Comment by Pe46dro** [comment]
You should check if intl extension is active in PHP 7.4

**Comment by DjSni** [comment]
thx a lot, works now
