### ISSUE TITLE
Error Message PHP 7.3

### ISSUE THREAD

**Issue by CookieCr2nk** [SergiX44/XBackBone#31]
**System Info**
+ PHP Version: PHP Version 7.3.3
+ XBackBone Version:  XBackBone v2.5.1
+ Webserver:  Apache/2.4.25 (Debian) 

**Describe the bug**
xBackbone don't have any restriction but it spams the error.log

Error.log Message: https://hastebin.com/ojujufosuq.cs

**To Reproduce**
1. The Error is spamming in the error.log of the Apache2 Log. The Error Message comes when i logging in xBackbone.

**Expected behavior**
-

**Comment by SergiX44** [comment]
This is a warning that the session path is not allowed to be overwritten by php apps (and the default system session path is used instead), check that the setting `session.save_path` is allowed to be overwritten in the php.ini or if you are using a web control panel.
