### ISSUE TITLE
[QUESTION] question about meta tags

### ISSUE THREAD

**Issue by Nevvy** [SergiX44/XBackBone#310]
Hello, I'm trying to re-create "Discord Embeds" feature from some sharex paid host
![chrome_8TKOYyA8Q9](https://user-images.githubusercontent.com/39029600/106389693-f93ab680-63e4-11eb-8847-672705fe77eb.png)

Iirc they are just adding extra meta-tags

```
<meta name="twitter:card" content="summary_large_image">
<meta id="discord" name="twitter:image" content="http://example.host/uploads/18950035-3647-4916-ab0c-d2e04161b467/hvd3ZKO3.png">
<meta id="embed-title" property="og:title" content="hvd3ZKO3.png (34.17 KB)">
<meta id="embed-desc" property="og:description" content="Uploaded at 1/31/2021, 2:52:30 PM by xyz">
<meta name="theme-color" content="#7873f5">
```
So i added those tags to resources/templates/upload/public.twig and rebuilded xbackbone cache
```
{% block head %}
    {% if type == 'image' %}
    <link rel="preload" href="{{ url }}/raw" as="{{ type }}">
    <meta name="og:image" itemprop="{{ type }}" content="{{ url }}/raw">
    <meta name="twitter:card" content="summary_large_image">
    <meta id="discord" name="twitter:image" content="{{ url }}/raw">
    <meta id="embed-title" property="og:title" content="{{ media.filename }}">
    <meta id="embed-desc" property="og:description" content="{{ config.app_name - xbackbone }}">
    <meta name="theme-color" content="#ff3232">
    {% endif %}
{% endblock %}
```
Unfortunately those meta tags are visible only on web-browser but not on discord
![Discord_iUD5oeNrK6](https://user-images.githubusercontent.com/39029600/106389739-3f901580-63e5-11eb-8903-d1b0454e42ec.png)
I tried to post a link with .png and without .png file extension but effect is the same
I decided to add those tags to base.twig for testing purposes and it works

![chrome_G8v9r7JU6n](https://user-images.githubusercontent.com/39029600/106389838-d6f56880-63e5-11eb-87f2-055015fc411e.png)
Could I get a hint which file should i modify to make it working?

Best regards, Nevvy

**Comment by josevazquz** [comment]
I've been trying to do the same thing for a while. Let me know if you figure it out. :)

**Comment by rossiscool123** [comment]
I tried doing something like this however it was caching the same image in my tests, the service is pays.host, and they're not paid for, it's an invite-only service with many domains.

**Comment by jacany** [comment]
Also trying to figure this out. It seems discord doesn't care at all if you send a xbackbone URL regardless, even if it's a text file or something, it won't display an embed.

**Comment by jacany** [comment]
I got it, a pull will be created when i finish the implementation of it

**Comment by jacany** [comment]
#322 My Pull

**Comment by rossiscool123** [comment]
Very nice @jacany, just added it to my xbackbone and worked first try. I'm assuming from your comment in the **base.twig** that you couldn't get video embeds to work. I tried using the **twitter:player** and **og:video** meta tags but they didn't work, I guess you tried the same. Great pull non the less.

**Comment by SergiX44** [comment]
Added implementation.
