### ISSUE TITLE
Stream failing for raw image (but thumbnails work fine)

### ISSUE THREAD

**Issue by mfkp** [SergiX44/XBackBone#311]
**System Info**
+ PHP Version: 7.4.14
+ XBackBone Version: v3.3.3 
+ Webserver: Apache
+ Database backend: SQLite

**Describe the bug**
None of my uploaded images are loading when in raw form, just getting an empty response. It's properly setting the content type header, but the content length gets set to 0:

```
content-type: image/jpeg
content-length: 0
```

The thumbnail images load fine though (presumably because the makeThumbnail function is returning an image, not a stream).

I've tracked it down to around here, but I don't know how to resolve this (maybe a setting on my server)? https://github.com/SergiX44/XBackBone/blob/cb48fe30eb20feeca5ebab23d09171eb0221ac79/app/Controllers/MediaController.php#L334-L350

**To Reproduce**
Check this sample image here: https://kyle.pp.ua/tEDA0/nASiDoWu04.jpg/raw (it will load blank, but can inspect response headers)

You can see that the thumbnail images work properly by adding a `width` or `height` param. Example: https://kyle.pp.ua/tEDA0/VaXOrUYU18.png/raw?width=500

**Expected behavior**
It should show the image ;-)

**Logs**
(nothing in the logs containing anything relevant, since it's not erroring, just returning a 0 size response)

**Comment by SergiX44** [comment]
Thats really weird, did you tried disable cloudflare? Maybe they are trying to cache that page.
Which storage driver do you use?

**Comment by mfkp** [comment]
Yes, just tried with cloudflare proxy disabled and it is the same result.

This is with s3 storage

**Comment by SergiX44** [comment]
Can you try to comment out the line at https://github.com/SergiX44/XBackBone/blob/master/bootstrap/container.php#L61 ?

**Comment by mfkp** [comment]
@SergiX44 commented that line, cleared cache, still has same issue :-/

**Comment by mfkp** [comment]
Note that it does seem to be an s3 specific issue. I just tried it with the FTP adapter and it works fine (of course since s3 seems to be the only adapter using the streaming feature, that would make sense).

**Comment by SergiX44** [comment]
Thats more strange, sadly I didnt have an s3 bucket to testing it right now. But if for other adapter works can be an issue of that specific adapter. Can you try run a `composer update`, maybe they deprecated something with recent versions, but I didn't check it out.

**Comment by SergiX44** [comment]
If you have some more news about the issue, feel free to reopen it.
