### ISSUE TITLE
Theme Doesn't Fully Apply

### ISSUE THREAD

**Issue by Ryonez** [SergiX44/XBackBone#312]
**System Info**
+ PHP Version: 7.2.27
+ XBackBone Version: 3.3.3
+ Webserver: Nginx
+ Database backend: SQLite
+ Docker Image: [Pe46dro/XBackBone-docker](https://github.com/Pe46dro/XBackBone-docker)

**Describe the bug**
I very much prefer dark themes. To this end I select the "slate" theme. However I've noticed that the background of the page doesn't change and it doesn't for any theme.
This makes the screen still pretty bright, and makes some elements hard to read as they expect a dark background.

**To Reproduce**
1. Set Theme to Solar
2. Observe

**Expected behavior**
The theme to fit everything.

**Screenshots**
![image](https://user-images.githubusercontent.com/16157130/107903338-dd6f0d00-6fad-11eb-89f5-e305cf150806.png)
![image](https://user-images.githubusercontent.com/16157130/107903424-14ddb980-6fae-11eb-85dc-b28e01a7124d.png)

**Comment by SergiX44** [comment]
The only theme supported is actually the default one, the one you choose are .css files download on-the-fly by bootswatch and applied on top of the default theme, so yeah some of it are not so good or change the behaviour of the default boostrap classes.
A dark theme that should look good is "spacelab" if i'm not wrong.

**Comment by Ryonez** [comment]
Looks like Slate is one of the few that doesn't change the background. Cyber is a theme that does and looks half decent.

Would we be able to ask for a custom css field in the settings, to allowed us to make changes/fixs for things like this please?

**Comment by SergiX44** [comment]
You can already put custom css rules in the settings, just put it in the head section:
```html
<style>
.customClass { ... }
</style>
```

**Comment by Ryonez** [comment]
I was not aware the header field would allow page changes, thank you.
