### ISSUE TITLE
HTTP 500 response when installing

### ISSUE THREAD

**Issue by Deverium** [SergiX44/XBackBone#316]
**System Info**
+ PHP Version: 8.0
+ XBackBone Version: 3.3.3
+ Webserver: Apache2
+ Database backend: SQLite
+ Ubuntu 20.04

**Describe the bug**
Upon clicking the install button in the installer, the page reports a 500 error.

**To Reproduce**
1. Download latest release
2. Run `sudo apt-get install php-sqlite3 php-mysql php-gd php-json php-intl php-zip php8.0-common` (php8.0 common includes php-fileinfo I believe? I can't install it standalone, it tells me to install that instead.)
3. Go to setup webpage
4. Insert install information
5. Click install
6. Error shows up

**Expected behavior**
It should install without problem

**Screenshots**
https://i.imgur.com/BYwrBIm.png

**Logs**
No logs were outputted. `sudo systemctl status apache2` shows no errors.

**Comment by rossiscool123** [comment]
You should have a php error log somewhere which would tell you the problem. Search up the control panel you're using and see if you can find an error log.

For me mine is in "account/logs/error_log"

**Comment by yuv41** [comment]
Try running chmod -r 777 *

**Comment by SergiX44** [comment]
> Try running chmod -r 777 *

This is not much raccomanded, you can cause security issues depending on the configuration.

> You should have a php error log somewhere which would tell you the problem. Search up the control panel you're using and see if you can find an error log.
> 
> For me mine is in "account/logs/error_log"

yes, you should try to find the php error log, but I'll gave it a shot installing with php8

**Comment by rossiscool123** [comment]
I've had issues rebuilding xbackbone where I've gotten a 500 error and the fix was as stupid as not having permission to generate a log file, Try giving all permissions to your log directory within the xbackbone installer. If you're using something like cPanel or virtualmin like me there are options for php to display errors within your web browser. https://i.imgur.com/lzdSwxE.png

**Comment by IntelligentCappy** [comment]
> I've had issues rebuilding xbackbone where I've gotten a 500 error and the fix was as stupid as not having permission to generate a log file, Try giving all permissions to your log directory within the xbackbone installer. If you're using something like cPanel or virtualmin like me there are options for php to display errors within your web browser. https://i.imgur.com/lzdSwxE.png

I'll try ths out and let you know.

**Comment by Deverium** [comment]
I couldn't seem to get anything to work, except for resetting the server and starting out fresh, then installing it normally.
