### ISSUE TITLE
Basic question

### ISSUE THREAD

**Issue by thesnowdog** [SergiX44/XBackBone#317]
I have managed to install XBackBone on my raspberry pi 4 with php 7.3 and lighttpd. The upload feature works fine. My question is how to load pre-existing files in the defined local storage folder. I am pointing my storage to /home/user/htpc which has subfolders and files including music, movies, and tv shows. I would like XBackBone to show those pre-existing files so I can use it as a basic web-based file manager. Is this not a feature? Am I missing something in my configuration?

Thanks

**Comment by SergiX44** [comment]
There is no import feature right now, BUT, you can use the bash script that xbackbone generates per user, and call it recursively on the files in folder, should be something like 
```sh
find . -type f | xargs bash <uploader>.sh
```
(not tested)
