### ISSUE TITLE
Uncaught Error: Call to undefined function App\\Web\\locale_accept_from_http()

### ISSUE THREAD

**Issue by rossiscool123** [SergiX44/XBackBone#318]
**System Info**
+ PHP Version: 7.4.15
+ XBackBone Version: 3.1.4
+ Webserver: Apache
+ Database backend: MySQL

**Describe the bug**
**PHP Fatal error:  Uncaught Error: Call to undefined function App\\Web\\locale_accept_from_http() in /home/domain.com/public_html/u/app/Web/Lang.php:61**

**To Reproduce**
Not sure how this error occurred, virtualmin just updated php and we kept getting this error in our apache logs.

**Screenshots**

**Logs**
Apache error log output

PHP Fatal error:  Uncaught Error: Call to undefined function App\\Web\\locale_accept_from_http() in /home/domain.com/public_html/u/app/Web/Lang.php:61\nStack trace:\n#0 /home/domain.com/public_html/u/resources/cache/di/CompiledContainer.php(84): App\\Web\\Lang::recognize()\n#1 [internal function]: CompiledContainer::{closure}()\n#2 /home/domain.com/public_html/u/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array()\n#3 /home/domain.com/public_html/u/vendor/php-di/php-di/src/CompiledContainer.php(116): Invoker\\Invoker->call()\n#4 /home/domain.com/public_html/u/resources/cache/di/CompiledContainer.php(85): DI\\CompiledContainer->resolveFactory()\n#5 /home/domain.com/public_html/u/vendor/php-di/php-di/src/CompiledContainer.php(53): CompiledContainer->get7()\n#6 /home/domain.com/public_html/u/resources/cache/di/CompiledContainer.php(90): DI\\CompiledContainer->get()\n#7 /home/domain.com/public_html/u/vendor/php-di/php-di/src/CompiledContainer.php(53): CompiledContainer->get8()\n#8 /home/ in /home/domain.com/public_html/u/app/Web/Lang.php on line 61

**Comment by rossiscool123** [comment]
Deleting **return locale_accept_from_http($_SERVER['HTTP_ACCEPT_LANGUAGE']);** from **app\Web\Lang.php** does fix the issue but I'd like to find a better fix for something like this. I'm not sure what the update to php has done to cause this.

**Comment by Pe46dro** [comment]
https://github.com/SergiX44/XBackBone/issues/307#issuecomment-761769713

**Comment by rossiscool123** [comment]
Yeah didn't have Intl installed silly me, thanks @Pe46dro.
