### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by freeshxyz** [SergiX44/XBackBone#32]
**System Info**
+ PHP Version: PHP 7.3.5-1+0-20190503093827.38+stretch-1.gbp60a41b
+ XBackBone Version: 2.5.1
+ Webserver: Apache/2.4.25 (Debian)

**Describe the bug**
I cannot install it. I try to go to the site but it throws an error.

**To Reproduce**
Try to install XBackbone using the following setup.

**Expected behavior**
I expect to get the install screen.

**Screenshots**
[https://sharex.freesh.xyz/2019/05/chrome_03_19-53-22.png](url)

Edit due to the version number not playing nicely with the formatting.

**Comment by SergiX44** [comment]
Are you sure that it's actually using php <= 7.1? Because that error is thrown because a typehint that is not recognized by php versions lower than 7.1.

**Comment by SergiX44** [comment]
Closed for inactivity. Feel free to reopen this issue if needed.
