### ISSUE TITLE
xbackbone needs a failed login attempt log.

### ISSUE THREAD

**Issue by danktankk** [SergiX44/XBackBone#320]
**Is your feature request related to a problem? Please describe.**
Currently, xbackbone will take endless logins, unless i am missing something.  This could potentially lead to brute force attacks, etc.

**Describe the solution you'd like**
Adding a log file for failed attempts so that fail2ban could be used to block the offender after x number of attempts.

**Additional context**
an xbackbone.conf file to include in the fail2ban filer.d folder wouud be a big help as well.

**Comment by rossiscool123** [comment]
Xbackbone has recaptcha support which might slow down repeated attacks but if you know you're being targeted you could pass the login page through cloudflare access so you'd have to authenticate that you're allowed to access that specific link. But it would be nice to see a max attempt timeout. 
I wouldn't be worried about bruteforce attacks as long as you're using a unique password.

**Comment by danktankk** [comment]
It isnt really about brute force attacks.  it is more about it being required for fail2ban to know how to respond to a possible intruder attempting to access the application.  I am hoping this could be integrated into a near future release as it is pretty much required for fail2ban to work.

**Comment by SergiX44** [comment]
I think it's a bit out of scope for xbackbone automatically integrate with 3rd software like fail2ban, also if you enable rechaptcha, it will filter out most of malicius bots. 

Anyway, from the 3.3.4 failed logins will be logged, writing a regex for fail2ban will be fairly easy for those who need it.
