### ISSUE TITLE
Discord Intergration

### ISSUE THREAD

**Issue by jacany** [SergiX44/XBackBone#323]
**Is your feature request related to a problem? Please describe.**
It would be nice to be notified on new file uploads, actions on accounts (like additions, deletions, and other events), and failed login attempts.

**Describe the solution you'd like**
I feel that using Discord Webhooks would be a great way of implementing this. Admins can configure a URL in the server's config, and get notifications on relevant events for security purposes.

**Comment by jacany** [comment]
This may also be able to solve #320

**Comment by danktankk** [comment]
Discord integration would be great as well, but I do not think it would be nearly as effective as fail2ban which literally sits and waits for intrusions whereas discord would merely report these events.

All I am asking for is a way to have xbackbone to write failed attempts to a file.  fail2ban will take care of the rest.

**Comment by SergiX44** [comment]
If you want that your logs will be redirected to discord, you can try to implement something like this: https://github.com/lefuturiste/monolog-discord-handler

and adding it somewhere after this line https://github.com/SergiX44/XBackBone/blob/master/bootstrap/container.php#L34

But I don't think is useful for mosts having this kind of feature.
