### ISSUE TITLE
Media upload timestamps are two hours off.

### ISSUE THREAD

**Issue by rossiscool123** [SergiX44/XBackBone#324]
**System Info**
+ PHP Version: 7.4.16
+ XBackBone Version: 3.1.4
+ Webserver: Apache
+ Database backend: MySQL

**Describe the bug**
Media timestamps are two hours ahead.

**Expected behavior**
Media uses the PHP timezone or local server timezone

Not sure if there's a config to change the timezone, I've tried changing the timezone settings within my php options and the timeserver for my server which reports my local time which is UTC +0

**Comment by rossiscool123** [comment]
I've also restarted Apache after making my chances and cleared my xbackbone cache to remove any variables.

**Comment by SergiX44** [comment]
You shoud check the timezone of you PHP installation, thats where the time is calculated.
