### ISSUE TITLE
make it easy for us to disable embeds

### ISSUE THREAD

**Issue by iphqne** [SergiX44/XBackBone#327]
**Is your feature request related to a problem? Please describe.**
I find the embed in this version quite useless and also annoying as it stops gifs from autoplaying on Discord

**Describe the solution you'd like**
A button like these
![image](https://user-images.githubusercontent.com/45533114/111350056-9f7f0a80-8679-11eb-8c28-dbbb924fdab9.png)
to disable embeds and maybe something even further to disable them for _specific_ file extensions

**Comment by rossiscool123** [comment]
@iphqne If you want to disable the embed option yourself you can add this right below **$filesystem = $this->storage;** in 
**/app/Controllers/MediaController.php**

        if (isBot($request->getHeaderLine('User-Agent'))) {
            return $this->streamMedia($request, $response, $filesystem, $media);
        }

Its not a clean way of disabling it since the meta tags remain but it will work on Discord and can be quickly enabled by removing them three lines of code. It looks like no one has a found a way for gifs and videos to embed yet so maybe that will be added in the future. Hope that helps your issue anyway. :)

**Comment by iphqne** [comment]
> @iphqne If you want to disable the embed option yourself you can add this right below **$filesystem = $this->storage;** in
> **/app/Controllers/MediaController.php**
> 
> ```
>     if (isBot($request->getHeaderLine('User-Agent'))) {
>         return $this->streamMedia($request, $response, $filesystem, $media);
>     }
> ```
> 
> Its not a clean way of disabling it since the meta tags remain but it will work on Discord and can be quickly enabled by removing them three lines of code. It looks like no one has a found a way for gifs and videos to embed yet so maybe that will be added in the future. Hope that helps your issue anyway. :)
> 
> Edit: You might need to clear your xbackbone cache to see the changes.

thank you, appreciate it

**Comment by That-Guy-Jack** [comment]
just going to reply as this would be useful as a normal switch

**Comment by iphqne** [comment]
> just going to reply as this would be useful as a normal switch

i agree, also gifs no longer embed properly (even if you append /raw)

**Comment by tigattack** [comment]
How will this help when [these lines](https://github.com/SergiX44/XBackBone/blob/3.3.4/app/Controllers/MediaController.php#L44.L46) have already existed for at least the last few versions?

**Comment by iphqne** [comment]
> How will this help when [these lines](https://github.com/SergiX44/XBackBone/blob/3.3.4/app/Controllers/MediaController.php#L44.L46) have already existed for at least the last few versions?

care to elaborate? i don't understand what
🤓if (isBot($request->getHeaderLine('User-Agent'))) {
            return $this->streamMedia($request, $response, $filesystem, $media);
        }🤓 means

**Comment by tigattack** [comment]
> > How will this help when [these lines](https://github.com/SergiX44/XBackBone/blob/3.3.4/app/Controllers/MediaController.php#L44.L46) have already existed for at least the last few versions?
> 
> care to elaborate? i don't understand what
> 🤓if (isBot($request->getHeaderLine('User-Agent'))) {
>             return $this->streamMedia($request, $response, $filesystem, $media);
>         }🤓 means

The fix specified [here](https://github.com/SergiX44/XBackBone/issues/327#issuecomment-800613117) already exists in the source.

**Comment by rossiscool123** [comment]
That fix only applies to the latest version of xbackbone that has the fancy meta tag embeds. Adding that code will force the image/video to just display without any meta tags. I'm not experienced with PHP I just know that adding it will remove the meta embed. There's a pull about this feature being added which you can just reverse and understand. #322 Or you can just downgrade one version where it wasn't added.

**Comment by rossiscool123** [comment]
You could even just remove all the meta tags from "resources/templates/base.twig" and clear your cache.

**Comment by tigattack** [comment]
I see. It looks like this was added in [3.0 RC4](https://github.com/SergiX44/XBackBone/blob/3.0.RC4/app/Controllers/MediaController.php#L43..L45), so it'd probably make more sense for people to just upgrade.

**Comment by SergiX44** [comment]
I don't think I want to bundle specific options for specific corner case for a specific platform, so I think I'll remove the embeds right away. If you want disable it right know, you can just put `Discord` in this array: https://github.com/SergiX44/XBackBone/blob/master/app/helpers.php#L325

**Comment by iphqne** [comment]
> I don't think I want to bundle specific options for specific corner case for a specific platform, so I think I'll remove the embeds right away. If you want disable it right know, you can just put `Discord` in this array: https://github.com/SergiX44/XBackBone/blob/master/app/helpers.php#L325

could you also fix gifs and videos not embedding on discord?

**Comment by SergiX44** [comment]
Removing the embed feature the media will be returned to discord like in the v3.3.3

**Comment by iphqne** [comment]
> Removing the embed feature the media will be returned to discord like in the v3.3.3

ok thank you

**Comment by iphqne** [comment]
@SergiX44 any information as to when this update is being pushed?

**Comment by That-Guy-Jack** [comment]
would be nice to have a update on this :>

**Comment by SergiX44** [comment]
Fixed in the release 3.3.5
