### ISSUE TITLE
Support for self-hosted S3 (i.e. Minio)

### ISSUE THREAD

**Issue by tigattack** [SergiX44/XBackBone#329]
**Is your feature request related to a problem? Please describe.**
I'd like to use an S3-compatible backend such as Minio, but currently only AWS S3 is supported.

**Describe the solution you'd like**
Support for self-hosted S3-compatible object storage services such as [Minio](https://min.io/).

**Comment by tigattack** [comment]
Apologies, I've just seen the [endpoint](https://github.com/SergiX44/XBackBone/blob/cb48fe30eb20feeca5ebab23d09171eb0221ac79/install/index.php#L137) option.

Perhaps this could be reflected in the docs? Considering it says "Amazon S3" and has no mention of the `endpoint` key in the docs [here](https://xbackbone.app/configuration.html#storage-drivers), it's very unclear that S3-compatible services are supported.

**Comment by tigattack** [comment]
I've reached a point where the configuration enables communication with Minio, but I'm seeing a `SignatureDoesNotMatch` error on upload.

The error is 
> SignatureDoesNotMatch (client): The request signature we calculated does not match the signature you provided. Check your key and signing method.

The configuration is
```php
    'storage' => [
        'driver' => 's3',
        'endpoint' => 'http://minio.speightnet.uk/minio',
        'key' => 'xbackbone',
        'secret' => 'i%9Ha2yj6$tsY7Cqz^Rq16PLyA@B3dZs',
        'region' => '',
        'bucket' => 'xbackbone',
        'path' => '',
    ],
```

Any pointers would be appreciated.

**Comment by SergiX44** [comment]
Hi, yes is not well documented actually, can you open a pr with the documentation update? Probably since you have already fixed you can provide better informations

**Comment by SergiX44** [comment]
Added to the docs
