### ISSUE TITLE
How to set uo the registration emails?

### ISSUE THREAD

**Issue by ARR4NN** [SergiX44/XBackBone#331]
Hello,
Could you assist me in explaing how to set up the email system
Thanks !

**Comment by 6K6666** [comment]
need help with this as well, not sure how to set up the email system

**Comment by SergiX44** [comment]
XBackBone uses the underlying PHP's `mail()` implementation to send emails, you should have installed a SMTP service on your system to allow to send emails:
https://code-boxx.com/fix-php-mail-not-working/
