### ISSUE TITLE
Pterodactyl hosting

### ISSUE THREAD

**Issue by ririko5834** [SergiX44/XBackBone#334]
Is it possible to host this on pterodactyl? Should I use this egg https://gitlab.com/tenten8401/pterodactyl-nginx ?

**Comment by Lebyy** [comment]
Depends if they have the egg, I use it on https://panel.hostarc.co and it works

**Comment by ririko5834** [comment]
What egg are you using?

**Comment by SergiX44** [comment]
If you find an egg with nginx/apache and php should works.
