### ISSUE TITLE
No Docker image for release 3.3.5

### ISSUE THREAD

**Issue by SDS1337** [SergiX44/XBackBone#335]
**System Info**
+ Docker Image: `pe46dro/xbackbone-docker:latest` (`3.3.4`)
+ XBackBone Version: `3.3.5`

**Description of Issue**
App reverts itself to previous version on container recreation since new image wasn't pushed with releasee `3.3.5`.

**To Reproduce**
1. While using the docker image, try to update XBackBone to `3.3.5`, which can be done via the self-installer.
2. Update completes successfully.
3. Stop and remove container. 
4. Recreate with same variables and paths.
5. XBackBone reverts itself to version `3.3.4`.

**Expected behavior**
Container respects newly upgraded files on start, does not revert back. Or, a new image is pushed along with the release.

**Comment by SergiX44** [comment]
https://github.com/Pe46dro/XBackBone-docker
/cc @Pe46dro
