### ISSUE TITLE
Bootswatch theme keeps getting reset after container recreation

### ISSUE THREAD

**Issue by SDS1337** [SergiX44/XBackBone#336]
**System Info**
+ Docker Image: `pe46dro/xbackbone-docker:latest`
+ XBackBone Version: `3.3.5`

**Description of Issue**
Bootswatch theme chosen in Settings keeps getting reset after docker container is recreated.

**To Reproduce**
1. While using the docker image, set any bootswatch theme from Settings page.
2. Stop, remove and recreate container with same variables, paths.
3. Theme is reset.

**Expected behavior**
Since the app stores its configuration in `/app` directories mounted from host, the theme should be persisting across container recreations.

**Comment by SergiX44** [comment]
The theme is stored on the `static/` directory, the last selected theme is stored on the database, but XBackBone can't know if the container is recreated to reapply the theme.
