### ISSUE TITLE
Discord embds not working

### ISSUE THREAD

**Issue by darius1727** [SergiX44/XBackBone#343]
**System Info**
+ PHP Version: 8.0.5
+ XBackBone Version: 3.3.5
+ Webserver: [Apache/Nginx/...] Nginx
+ Database backend: [SQLite/Mysql/...] MySQL

**Describe the bug**
When sending the image on discord the embed isn't showing up, just the plain image.

**To Reproduce**
1. Upload an image
2. Send link on Discord
3. Embed not showing.

**Expected behavior**
I expected to show the embed as it should be by looking at the source:
![image](https://user-images.githubusercontent.com/47954928/120893708-46da6080-c61d-11eb-8b05-b8c39969db64.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/47954928/120893716-640f2f00-c61d-11eb-8d62-9727a9ff16ed.png)

**Comment by SergiX44** [comment]
Since the version 3.3.5 the embed support was removed, because it causes weird this when embedding video or audio (probably is not supported properly by discord)
