### ISSUE TITLE
Uploader Addition: MagicCap

### ISSUE THREAD

**Issue by verttex** [SergiX44/XBackBone#345]
Hey there,

uPic wasn't working for me on Apple Silicon so I installed [MagicCap](https://github.com/MagicCap/MagicCap) and was able to get uploads working. Just thought you could add to the documentation for other MacOS users.

URL: `share url with /upload`
Image Body: `file`
Response Key: `url`
Headers:
`Content-Type` - `application/x-www-form-urlencoded`
`token` - `token from xbackbone`

**Comment by SergiX44** [comment]
Documentation added
