### ISSUE TITLE
Web Interface Settings seem to be broken a bit

### ISSUE THREAD

**Issue by PeterStrick** [SergiX44/XBackBone#347]
**System Info**
+ PHP Version: 7.4.13 x64
+ XBackBone Version: 3.3.5
+ Webserver: [Apache/Nginx/...] Microsoft IIS 10.0 running on Windows 10
+ Database backend: [SQLite/Mysql/...] SQLite

**Describe the bug**
Some Settings like the Theme ComboBox or the User Token Creation/Update Button won't load/work at all. 
Tested in Microsoft Edge Dev, Internet Explorer 11, Google Chrome on Android.

**To Reproduce**

[Theme ComboBox]
1. Go to Menu > System
2. Press on the Theme Combobox and select a Theme
(I worked around this issue by running `php ./bin/theme Lumen`

[User Token Creation/Update Button]
1. Go to Menu > Users
2. Edit the User admin
3. See that the Token Textbox is empty and try to click on "Update"

**Expected behavior**
These Features should work normally but instead display nothing in the case of the Combobox or don't do anything in the case of the Button.

**Screenshots**
[Theme Combobox] 
![ThemeIssue](https://user-images.githubusercontent.com/60312421/123260265-a8437000-d4f5-11eb-8020-6202737ee33c.gif)

[Token Update Button]
![TokenIssue](https://user-images.githubusercontent.com/60312421/123260305-b4c7c880-d4f5-11eb-87f3-91753cc684ca.gif)

**Logs**
[log-2021-06-24.txt - XBackBone Log](https://github.com/SergiX44/XBackBone/files/6709041/log-2021-06-24.txt)
[u_ex210624.log - IIS Log](https://github.com/SergiX44/XBackBone/files/6709056/u_ex210624.log)

This is a fresh install of WIndows and XBackBone.

**Comment by PeterStrick** [comment]
Found a workaround for the Token Update issue by creating a new User.
Everything else seems to work, including uploading over the Web Interface, uploading over ShareX, downloading the ShareX Client Configuration, etc.

**Comment by PeterStrick** [comment]
Edit: I found out that these Issues seem to occur because XBackBone was instructed to use HTTP at the installation phase, while Cloudflare was configured to HTTP traffic to HTTPS. Changing the base URL in the config.php from HTTP to HTTPS fixed the issues!

**Comment by VadSzil42** [comment]
Yes - I know that this is a 4 yr old issue - but i actually thought your mail was indeed nomail@4u.com LOL
