### ISSUE TITLE
please restore embed on discord to photos

### ISSUE THREAD

**Issue by nowehity97** [SergiX44/XBackBone#348]
re-adding embed to discord on photos 

![rjtpT](https://user-images.githubusercontent.com/48099875/123291114-1a29b280-d512-11eb-9501-c51e5a13a603.png)
example ^

**Comment by rossiscool123** [comment]
Its easy enough to re-enable yourself.

**Comment by rossiscool123** [comment]
I just removed

            'Discordbot/',
            'discord',

from helpers.php line 322, just make sure you have the meta tags in your base.twig inside your resources folder.

**Comment by rossiscool123** [comment]
If its not there add this under the script closing tag

`    
    <meta id="embed-url" property="og:url" content="{{ url }}">
    
    {% if type %}
    <meta name="twitter:card" content="summary_large_image">
    <meta property="og:type" content="website" />
    <meta id="embed-title" property="og:title" content="{{ media.filename }} ({{ media.size }})">
    <meta id="embed-image" property="og:image" content="{{ url }}/raw">
    <meta id="embed-desc" property="og:description" content="Uploaded at {{ media.timestamp }} by {{ media.username }}">
    <meta id="discord" name="twitter:image" content="{{ url }}/raw">
    <meta id="image-src" name="twitter:image:src" content="{{ url }}/raw">
    {% else %}
    <meta id="embed-title" property="og:title" content="{{ block('title') }}">
    <meta id="discord" name="twitter:image" content="/static/images/favicon-32x32.png">
    <meta id="image-src" name="twitter:image:src" content="/static/images/favicon-32x32.png">
    <meta id="embed-image" property="og:image" content="/static/images/favicon-32x32.png">
{% endif %}
    {% block head %}{% endblock %}
    {{ customHead|raw }}`

**Comment by SergiX44** [comment]
Maybe will be implented in the future as optional feature, but readding the embeds will break the preview of other kinds of media other than images.

**Comment by andrew121410** [comment]
Photo's seem to embed just fine without changing anything for me except .mp4 files would anyone know how to fix that?
