### ISSUE TITLE
Bootstrap alert styling looks wrong.

### ISSUE THREAD

**Issue by GilbN** [SergiX44/XBackBone#349]
**System Info**
+ PHP Version: 7.4.19
+ XBackBone Version: v3.3.5
+ Webserver: Nginx
+ Database backend: Sqlite

**Describe the bug**
Hi. Looks like the styling on the alert class is a bit broken. 

**To Reproduce**
1. Go to settings
2. Click on apply
3. See wierd styling on alert

**Expected behavior**
For it to look like it does in the bootstrap docs https://getbootstrap.com/docs/5.0/components/alerts/#dismissing

**Screenshots**
![chrome_F5I8rQhdsU](https://user-images.githubusercontent.com/24592972/124004053-eb12b580-d9d7-11eb-90b7-374343bb4547.png)

**Logs**
XBackBone and/or webserver logs.

**Comment by SergiX44** [comment]
Which browser are you using?

**Comment by GilbN** [comment]
> Which browser are you using?

Hi. It happens on:
Chrome 92.0.4515.107 
Edge Dev 93.0.961.7 
Brave | 1.27.109 Chromium: 92.0.4515.115
Firefox 90.0.2

**Comment by SergiX44** [comment]
If you open the developer console, can you see errors?

**Comment by GilbN** [comment]
> If you open the developer console, can you see errors?
No, not any errors. 
![](https://selfhosted.app/f3c10/XUMifuhe82.png/raw)

**Comment by SergiX44** [comment]
I think you have installed bootstrap 5 in some way, XBackBone uses bootstrap 4.

**Comment by GilbN** [comment]
lol, yeah I think I might have messed with the bootstrap files and completely forgot or something. Just updated to the latest and it looks ok now :) Sorry for the confusion..lol
