### ISSUE TITLE
Add default display option "Raw" and "UI"

### ISSUE THREAD

**Issue by Ente** [SergiX44/XBackBone#352]
It would be really nice, if it would be possible, that you could change the default view of the images and other files by raw.

Like in the System Nav could be a button in which a default display option could be "Raw" and "UI".

It's just how I like it, but yea. Idk if it would be nice for others too.

**Comment by SergiX44** [comment]
I think its a duplicated of this: https://github.com/SergiX44/XBackBone/issues/291
