### ISSUE TITLE
Discord Embeds

### ISSUE THREAD

**Issue by That-Guy-Jack** [SergiX44/XBackBone#363]
**System Info**
+ PHP Version: 8.0
+ XBackBone Version: 3.4.0
+ Webserver: Apache
+ Database backend: Mysql

**Describe the bug**
Updated to V3.4.0 and discord emebeds have broken as images don't fully embed as in previous verstion

**To Reproduce**
upload any image to xbackbone

**Expected behavior**
Ment  to Embed fully without meta tags/rich embed

**Screenshots**
![image](https://user-images.githubusercontent.com/56127525/128651055-3e9c6e7a-6b55-48d2-9803-e6b2ccab1108.png)

**Logs**
XBackBone and/or webserver logs.

**Comment by SergiX44** [comment]
Next release will include toggle for this

**Comment by That-Guy-Jack** [comment]
Sounds Good, is there a ETA on when the next release is? or is it soon ™️

**Comment by SergiX44** [comment]
Added in the latest release.
