### ISSUE TITLE
FTP-Server

### ISSUE THREAD

**Issue by MrUnknownDE** [SergiX44/XBackBone#37]
Hello,

Maybe a little idea.
Whether one implements a function which makes it possible to outsource image files (or all files) to external FTP servers.

Best regards
Johannes K.

**Comment by SergiX44** [comment]
How this functionality could be useful? If you want to upload media to an ftp sharex has already that option.

**Comment by MrUnknownDE** [comment]
This is so true but I would like to give other users no access to my FTP server and there just just this solution in the sense.

**Comment by SergiX44** [comment]
Added in 2.6
