### ISSUE TITLE
Can't get xbackbone to work on my webserver at all

### ISSUE THREAD

**Issue by PhoenixAceVFX** [SergiX44/XBackBone#389]
**System Info**
+ PHP Version: 7.2.34
+ XBackBone Version: 3.5.0
+ Webserver: [Apache/Nginx/...] Apache
+ Database backend: [SQLite/Mysql/...] MySQL

**Describe the bug**
I've undergone the installation on the webserver several times but no matter what i get no styling of any kind nor can i even attempt to login. i'm using a windows VM running xampp and ive done just about everything i can think of.

**To Reproduce**
All im doing is doing the install

**Expected behavior**
![image](https://user-images.githubusercontent.com/38572203/134225824-f251ed56-f71a-4660-872e-c8282042fdce.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/38572203/134225951-37b5e44a-d87d-4015-b7d2-956500a3bdfe.png)

**Logs**
No logs involving xbackbone are appearing

**Comment by PhoenixAceVFX** [comment]
if i try to login i just get sent back to the login screen

**Comment by SergiX44** [comment]
Did you check the requirements about extensions and mod_rewrite for apache? 
There is probably an issue over there i think.
Can you post the developer console if actually loads CSS/JS?

**Comment by PhoenixAceVFX** [comment]
i checked all the requirements and it has everything it needs
as for the issue, i found what caused it, i had forgotten to configure it to HTTPS instead of HTTP

**Comment by PhoenixAceVFX** [comment]
alright i can confirm my issue is solved
