### ISSUE TITLE
Copy RAW URL Option does nothing

### ISSUE THREAD

**Issue by Fabl0s** [SergiX44/XBackBone#391]
**System Info**
+ PHP Version: 7.4.2.1
+ XBackBone Version: 3.5.0
+ Webserver: [Apache/Nginx/...] Apache
+ Database backend: [SQLite/Mysql/...] MySQL

**Describe the bug**
Selecting the RAW URL Option doesnt get Included in when Creating ShareX Configs.

**To Reproduce**
Login
Goto Profile
Set Copy Mode to RAW URL
Download new Config
Apply in ShareX
Create Screenshot
Get a normal Link an not a /raw link

**Expected behavior**
Expeted to get a /raw Link into Clipboard

**Screenshots**

**Logs**
XBackBone and/or webserver logs.

Doublechecked in the Created Profiles:
`{
    "DestinationType": "ImageUploader, TextUploader, FileUploader",
    "RequestURL": "***",
    "FileFormName": "upload",
    "Arguments": {
        "file": "$filename$",
        "text": "$input$",
        "token": "***"
    },
    "URL": "$json:url$",  <== Should Include /raw aswell?
    "ThumbnailURL": "$json:url$/raw",
    "DeletionURL": "$json:url$/delete/token_*****************************"
}`

**Comment by SergiX44** [comment]
The raw url copy is only for copy link on the web ui
