### ISSUE TITLE
discord no longer embedding

### ISSUE THREAD

**Issue by iphqne** [SergiX44/XBackBone#397]
**System Info**
+ PHP Version: 7.4
+ XBackBone Version: 3.5.0
+ Webserver: [Apache/Nginx/...] https://www.litespeedtech.com/
+ Database backend: [SQLite/Mysql/...] sqlite

**Describe the bug**
Discord is no longer embedding images that are sent UNLESS "/raw" is appended to the image or the "embed images" option is on

**To Reproduce**
1. Upload an image using xbackbone
2. Post it to discord
3. Watch it not embed

**Expected behavior**
The image to actually embed

**Screenshots**
https://iphqne.com/-/SiLo9/jaYaLOmA74.gif/raw
![d08g70I7wr](https://user-images.githubusercontent.com/45533114/137547432-242352f4-14dd-4f16-8ad3-c9a95889e5e6.gif)
https://iphqne.com/-/SiLo9/NOYiculA58.gif/raw
![xqdSgwYyCK](https://user-images.githubusercontent.com/45533114/137547614-c8a20079-fce1-4070-91dc-3ca867b956ae.gif)

I think discord have maybe changed something in the way they embed images and because the normal url isn't an actual raw image it's struggling to embed.

**Comment by Skizzles** [comment]
Having exact same issues.

**Comment by iphqne** [comment]
just tested the video issue, same for me.

**Comment by Vondyy** [comment]
Pictures also doesn't always embed for me even if I say /raw same with my budyd who host his own instance. Sometimes it does sometimes it doesn't. It doesn't embed without /raw like it used to
