### ISSUE TITLE
Refuses to embed on discord

### ISSUE THREAD

**Issue by Vondyy** [SergiX44/XBackBone#405]
**System Info**
+ PHP Version: 7.43
+ XBackBone Version: latest just updated and still have same issue
+ Webserver: [Apache/Nginx/...] apache
+ Database backend: [SQLite/Mysql/...] i think sqlite not sure

**Describe the bug**
I take a screenshot and it auto copies to my clipboard using sharex, then whenever I post it on discord it refuses to embed. A slight obnoxious work around is everytime type in /raw at the end. Also, copy url mode to raw doesnt work. Please fix

**To Reproduce**
1. Take screenshot
2. Paste on discord
3. Doesnt embed

**Expected behavior**
embed on discord

**Comment by SergiX44** [comment]
There is a switch in the settings, that enable embedding images instead displaying the raw image (second image in the screenshot)
![image](https://user-images.githubusercontent.com/4172890/139707569-9dad46de-f198-4c80-b76c-f19670e28b21.png)

Anyway, as you can see both methods works fine to me, so I suggest to check your settings since Discord some time ago changed its User agent, so maybe can be something related to your config

**Comment by rossiscool123** [comment]
@SergiX44 The issue isn't backbone but more along Discord, they seem to of banned a bunch of free TLD's as a domain of mine ending in .tk stopped working with the rise of all the fake nitro links. I tested it by creating a test meta page with these test meta tags.

```
<title>Meta Tags — Preview, Edit and Generate</title>
<meta name="title" content="Meta Tags — Preview, Edit and Generate">
<meta name="description" content="With Meta Tags you can edit and experiment with your content then preview how your webpage will look on Google, Facebook, Twitter and more!">
<meta property="og:type" content="website">
<meta property="og:url" content="https://metatags.io/">
<meta property="og:title" content="Meta Tags — Preview, Edit and Generate">
<meta property="og:description" content="With Meta Tags you can edit and experiment with your content then preview how your webpage will look on Google, Facebook, Twitter and more!">
<meta property="og:image" content="https://metatags.io/assets/meta-tags-16a33a6a8531e519cc0936fbba0ad904e52d35f34a46c97a2c9f6f7dd7d336f2.png">
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="https://metatags.io/">
<meta property="twitter:title" content="Meta Tags — Preview, Edit and Generate">
<meta property="twitter:description" content="With Meta Tags you can edit and experiment with your content then preview how your webpage will look on Google, Facebook, Twitter and more!">
<meta property="twitter:image" content="https://metatags.io/assets/meta-tags-16a33a6a8531e519cc0936fbba0ad904e52d35f34a46c97a2c9f6f7dd7d336f2.png">
```
No surprise they did not work on a .tk domain, failed to embed, not a single GET request from Cloudflare and even Apache didn't serve a cloudflare IP. Another story with my .com, .net and .rocks domain which all did a GET request to that index.html.

The issue isn't backbone but more of Discord being retarded and banning TLD extensions without a blog post.

**Comment by rossiscool123** [comment]
@Vondyy

**Comment by Vondyy** [comment]
My issue was having this selected https://xbb.speedygoat.net/dUJU7/TEHUFOzO27.png turning this off fixed it
