### ISSUE TITLE
Discord embeded videos not playing (3.5.1)

### ISSUE THREAD

**Issue by That-Guy-Jack** [SergiX44/XBackBone#409]
**System Info**
+ PHP Version: 8.0
+ XBackBone Version: 3.5.1
+ Webserver: Nginx
+ Database backend: Mysql

**Describe the bug**
Discord embeds videos but it can't play as time is just 0:00

https://user-images.githubusercontent.com/56127525/139151356-c1647762-0588-4cac-8568-ac80cad07720.mp4

FYI link to the video `https://cdn.thatguyjack.co.uk/Pibi1/JItETOYe91.mp4`

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to discord
2. paste link to video 
3. embeds but can't play
4. Profit?

**Comment by LobaDK** [comment]
Getting the exact same issue here, only difference is my webserver is Apache, and I'm running PHP 7.4.25.

**Comment by That-Guy-Jack** [comment]
Any idea on this @SergiX44 ?

**Comment by SergiX44** [comment]
Can you try if https://cdn.thatguyjack.co.uk/Pibi1/JItETOYe91/raw.mp4
works for you?

**Comment by That-Guy-Jack** [comment]
> Can you try if https://cdn.thatguyjack.co.uk/Pibi1/JItETOYe91/raw.mp4 works for you?

![image](https://user-images.githubusercontent.com/56127525/139707293-f8b95e50-39b2-4245-b784-043a7af86b21.png)
yup that works perfectly what a weird  bug

**Comment by SergiX44** [comment]
I need to investigate if discord is doing some weird stuff, as always :angry:

**Comment by LobaDK** [comment]
Appending /raw doesn't seem to work or fix it for me, and instead Discord refuses entirely to embed the video.

**Comment by That-Guy-Jack** [comment]
> Appending /raw doesn't seem to work or fix it for me, and instead Discord refuses entirely to embed the video.

You need to make sure its /raw.mp4

**Comment by LobaDK** [comment]
> 
> 
> > Appending /raw doesn't seem to work or fix it for me, and instead Discord refuses entirely to embed the video.
> 
> You need to make sure its /raw.mp4

ah that would make sense, silly me. Guess I'll use this as a momentary fix

**Comment by Vondyy** [comment]
Screenshots doesn't always embed for me either, even if I include raw. Sometimes, it'll embed for me and not for others. Vice versa.

**Comment by Vondyy** [comment]
![image](https://user-images.githubusercontent.com/83143426/141408814-ae8d9f47-7e0a-4fc9-b8fc-a01a08f89fec.png)
also sometimes it will display if you click on the image itself

**Comment by LobaDK** [comment]
@Vondyy 
Images embeds fine for me, even larger ones around 30-40MB. Since you mention it does sometimes embed for others but not you, and vice versa, as well as sometimes showing the embed when you click on it, I am willing to bet this is an issue with your server’s location, the internet or a mix of discord’s embed servers having issues downloading the image, and the client just being buggy as it always seems to be.

**Comment by SergiX44** [comment]
@Vondyy please keep this issue in-topic. As @LobaDK said could be a mix of different reasons. I've tried in the past to reproduce it from my dedicated server and local environment but even with big images and gifs every time worked.
Recently Discord changed some stuff apparently and a fix for the image embedding is already released.

**Comment by JReverse** [comment]
Any ETA?

**Comment by rossiscool123** [comment]
If your website is behind cloudflare check your firewall logs. In my case I needed to whitelist this IPv6 address in my firewall which was actually blocking videos from playing, the thumbnail will embed but videos will not play without this IPv6 whitelisted.

2a06:98c0:3600::103

**Comment by LobaDK** [comment]
> If your website is behind cloudflare check your firewall logs. In my case I needed to whitelist this IPv6 address in my firewall which was actually blocking videos from playing, the thumbnail will embed but videos will not play without this IPv6 whitelisted.
> 
> 2a06:98c0:3600::103

Using Cloudflare and got no firewall logs at all here. Furthermore even with the proxy disabled it's still broken.

**Comment by Skizzles** [comment]
Any update on this?

**Comment by GabrielSerealia** [comment]
I seem to be experiencing a similar issue where the embeds show the thumbnail but don't play at all.

Video Used: https://i.serealia.ca/puGE3/saCiWugA02.webm
What it looks like in Discord: https://i.serealia.ca/puGE3/naqewUYo55.webm

**Comment by ImMaxUK** [comment]
Getting the same issue here, if I append /raw to the end of my videos it embeds. Otherwise it refuses to play on Discord.

**Comment by DarkAnturian** [comment]
> I seem to be experiencing a similar issue where the embeds show the thumbnail but don't play at all.
> 
> Video Used: https://i.serealia.ca/puGE3/saCiWugA02.webm What it looks like in Discord: https://i.serealia.ca/puGE3/naqewUYo55.webm

same issue here, was ok for a day after reinstalling OS. then it started up again.

**Comment by SergiX44** [comment]
I've implented kind of a workaround for this strange behaviour that discord has, if no embed enabled and the video is larger than 8mb, it forces the embedding in this commit https://github.com/SergiX44/XBackBone/commit/1979c3f3183f27c086d6c04335f645071d54014c
I'll be up with the next release.
