### ISSUE TITLE
Can't upload images via ShareX after updating to newest version

### ISSUE THREAD

**Issue by derMiepz** [SergiX44/XBackBone#410]
**System Info**
+ PHP Version: 7.3.31
+ XBackBone Version: v3.5.1
+ Webserver: Nginx
+ Database backend: Mysql

**Describe the bug**
After updating from a rather old version, I'm unable to upload images via ShareX because I get an 503 "Endpoint under maintenance" error.

**To Reproduce**
1. Try to upload an image via ShareX
2. See error

**Expected behavior**
The image should upload

**Screenshots**
![image](https://user-images.githubusercontent.com/45405525/139734179-ac63b559-41f0-43af-9ad4-41874a1216ff.png)

**Logs**
`2001:16b8:2243:6100:1db0:66d8:97eb:5b92 - - [01/Nov/2021:21:00:44 +0100] "POST /upload HTTP/1.0" 503 582 "-" "ShareX/13.6.1"
2001:16b8:2243:6100:1db0:66d8:97eb:5b92 - - [01/Nov/2021:21:00:45 +0100] "POST /upload HTTP/1.0" 503 582 "-" "ShareX/13.6.1"
2001:16b8:2243:6100:1db0:66d8:97eb:5b92 - - [01/Nov/2021:21:01:02 +0100] "POST /upload HTTP/1.0" 503 582 "-" "ShareX/13.6.1"`

**Comment by LobaDK** [comment]
Is the maintenance mode flag in config.php set to true by any chance?

**Comment by derMiepz** [comment]
Yes it was enabled and setting it to false fixed it, but I never changed anything in there. Could that be a bug in the updater?

**Comment by LobaDK** [comment]
When you use the update function in the admin panel, it momentarily enables maintenance mode, which I assume acts as a form of protection while updating, in case any user attempts to upload or login. It failed to disable it again, or you forgot to click continue after the update finished, which I believe is required before the service automatically disables it.

**Comment by derMiepz** [comment]
Hmm I see. Either way, it would be nice to have some kind of indication that the maintenance mode is enabled with either a button to disable it right in the dashboard, or with a hint that it's in the config.php. :D

**Comment by LobaDK** [comment]
Not exactly a hint, but the [configuration documentation](https://xbackbone.app/configuration.html#maintenance-mode) does mention how and where to enable or disable maintenance mode, and as you even showed yourself, the server does return the message "Endpoint under maintenance" error.

Though I will agree that it would be nice to have a form of indication in the admin panel, that maintenance mode is enabled.

**Comment by derMiepz** [comment]
Not everyone remembers to check the config docs when the initial install was a while ago, but I'll make sure to take a look at it again when encountering problems, thanks!
