### ISSUE TITLE
Custom HTML content not saving

### ISSUE THREAD

**Issue by ShrootBuck** [SergiX44/XBackBone#414]
I put this into the HTML content
`<script src="https://pastebin.com/raw/MyJavaScriptCode.js"></script>`

And got redirected to `https://mydomain.gg/host/system/settings/save` and given an Error 403. Not sure why this is happening, cause I've been able to get some JS to work and others not.

**Comment by SergiX44** [comment]
![image](https://user-images.githubusercontent.com/4172890/174581474-ee4a46bc-cb50-4ade-9b28-54e854b6704c.png)

To me works as expected.
There is something wrong I think on your setup I think.
