### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by anondev-sudo** [SergiX44/XBackBone#417]
Hi I am getting error 500 when I visit the url. 

```
AH01071: Got error 'PHP message: PHP Warning: require(/var/www/hosting/web870/web/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/hosting/web870/web/index.php on line 4PHP message: PHP Fatal error: require(): Failed opening required '/var/www/hosting/web870/web/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/hosting/web870/web/index.php on line 4'
```

**Comment by anondev-sudo** [comment]
Fixed this by running npm install, but now I have different problem.
Install looks like this 
![image](https://user-images.githubusercontent.com/85408287/145821598-a4a83bfb-2338-4c6d-98ba-d53a2f393aff.png)
css and js is missing.

![image](https://user-images.githubusercontent.com/85408287/145821647-99a63710-f57d-457e-b663-9edf59037a32.png)
It's throwing too many redirects when I visit the urls.
In website access logs:
![image](https://user-images.githubusercontent.com/85408287/145821738-d11f6d31-6c17-43b2-91d9-0af60e8c6ea0.png)
It seems to be some problem with redirecting, maybe .htaccess file is wrong? I have cloned the latest version from github.

**Comment by SergiX44** [comment]
> Fixed this by running npm install, but now I have different problem. Install looks like this ![image](https://user-images.githubusercontent.com/85408287/145821598-a4a83bfb-2338-4c6d-98ba-d53a2f393aff.png) css and js is missing.
> 
> ![image](https://user-images.githubusercontent.com/85408287/145821647-99a63710-f57d-457e-b663-9edf59037a32.png) It's throwing too many redirects when I visit the urls. In website access logs: ![image](https://user-images.githubusercontent.com/85408287/145821738-d11f6d31-6c17-43b2-91d9-0af60e8c6ea0.png) It seems to be some problem with redirecting, maybe .htaccess file is wrong? I have cloned the latest version from github.

If have cloned it from github, you need to run composer, npm and grunt to install and build all the dependencies, otherwise, download the release.zip from the releases that already has all prepackaged

**Comment by anondev-sudo** [comment]
Ok I ran npm install and composer install, is `grunt` command or `grunt install`?

**Comment by anondev-sudo** [comment]
After running grunt I get this
```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'liftoff'
Require stack:
- /usr/share/nodejs/grunt-cli/bin/grunt
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/share/nodejs/grunt-cli/bin/grunt:7:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/share/nodejs/grunt-cli/bin/grunt' ]
}
```

**Comment by anondev-sudo** [comment]
Fixed it

**Comment by anondev-sudo** [comment]
I have problem with S3 storage, I selfhost minio for S3, I have provided s3 settings in config.php but I am getting errors that it can't resolve `bucketname.s3.mydomain.com`. minIO is path based, it does not create subdomain for each bucket. What should I set in the config to make it work?

**Comment by anondev-sudo** [comment]
> I have problem with S3 storage, I selfhost minio for S3, I have provided s3 settings in config.php but I am getting errors that it can't resolve `bucketname.s3.mydomain.com`. minIO is path based, it does not create subdomain for each bucket. What should I set in the config to make it work?

I found that there is `'use_path_style_endpoint' => true,` option in AWS S3 php wrapper, but how to activate it in XBackBone?

**Comment by anondev-sudo** [comment]
Found it

**Comment by anondev-sudo** [comment]
Sorry for email spam

**Comment by anondev-sudo** [comment]
I tried to edit this file 
![image](https://user-images.githubusercontent.com/85408287/145945068-3d1b1386-b7e9-48f9-b0d9-a554db69d68f.png)
but changes did not appear, why?

**Comment by LobaDK** [comment]
> I tried to edit this file ![image](https://user-images.githubusercontent.com/85408287/145945068-3d1b1386-b7e9-48f9-b0d9-a554db69d68f.png) but changes did not appear, why?

Pretty sure xbackbone has a cached version that you need to delete from the cache folder, whenever you make changes to the template files. There's a lot of subfolders in the cache folder, but you should be able to locate the base.twig file with something like the `find` command, and then simply delete it to force xbackbone to re-cache it.
