### ISSUE TITLE
S3 List Objects

### ISSUE THREAD

**Issue by LubricantJam** [SergiX44/XBackBone#424]
**System Info**
+ PHP Version: 7.4.26
+ XBackBone Version: 3.5.1
+ Webserver: NGINX
+ Database backend: MySQL

**Describe the bug**
When adding an S3 Compatible bucket, it seems S3 List Objects is being ran every page refresh. This is alarming because the service I use and probably many others, charge for this query being ran.

**To Reproduce**
1. Add a S3 Compatible Bucket, like BackBlaze B2.
2. Go to the Report section and view the transactions being ran (creating a bucket is free and is free up to a certain amount of uses then it's charged so feel free to make one).
3. Then witness the amount of queries being ran, I only have 400 files and have only just added this bucket, so this is data purely from a couple hours. (https://i.jdf.gg/SULU6/ZUnuTEsa14.png)

**Expected behavior**
 If there was a way to somehow cache this list and if anything is upload to then grab the new object list, this would be suffice. Currently it's talking to the bucket WAY too much and even is slowing down page speeds drastically and takes a few seconds for the page to completely load. This did not happen on local storage, of course.

**Comment by SergiX44** [comment]
The S3 implementation relies fully on the flysystem library implementation, I try look into it.
Maybe deferring the actual storage instantiation to the actual usage may fix this weird behaviour
