### ISSUE TITLE
Dropzone Error Docker

### ISSUE THREAD

**Issue by jxrse** [SergiX44/XBackBone#425]
**System Info**
+ PHP Version:  7.4.26
+ XBackBone Version: Actualizacionesv3.5.1
+ Webserver: [Apache/Nginx/...]
+ Database backend: [SQLite/Mysql/...] SQlite

**Describe the bug**
After installing it for the first time in docker through the portainer on a Raspberry pi it won't let me upload files, I get an error on the console

** Console Errors*
DevTools failed to load source map: Could not load content for http://192.168.1.89:8200/static/bootstrap/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.1.89:8200/static/bootstrap/js/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.1.89:8200/static/plyr/plyr.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.1.89:8200/static/bootstrap/js/bootstrap4-toggle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
dropzone.min.js?1640221778:1 Uncaught TypeError: Cannot read properties of undefined (reading 'error')
    at i.error (app.js?1640221778:1)
    at i.value (dropzone.min.js?1640221778:1)
    at i.value (dropzone.min.js?1640221778:1)
    at dropzone.min.js?1640221778:1
    at i.value (dropzone.min.js?1640221778:1)
    at i.value (dropzone.min.js?1640221778:1)
    at HTMLInputElement.<anonymous> (dropzone.min.js?1640221778:1)
error @ app.js?1640221778:1
value @ dropzone.min.js?1640221778:1
value @ dropzone.min.js?1640221778:1
(anonymous) @ dropzone.min.js?1640221778:1
value @ dropzone.min.js?1640221778:1
value @ dropzone.min.js?1640221778:1
(anonymous) @ dropzone.min.js?1640221778:1

**Comment by SergiX44** [comment]
I don't know, it seems that there are some assets missing. Please contact the author of the docker image.
