### ISSUE TITLE
HTTP Error 500

### ISSUE THREAD

**Issue by SamIsOnMC** [SergiX44/XBackBone#429]
**System Info**
+ PHP Version: 7.2
+ XBackBone Version: Latest / Dev Build (Cloned from git repo)
+ Webserver: [Apache/Nginx/...] Apache
+ Database backend: [SQLite/Mysql/...] ?????????

**Describe the bug**

**To Reproduce**
1. Go to 'the document root'
2. See error

**Expected behavior**
The web installer
**Screenshots**

**Logs**
XBackBone and/or webserver logs.
Dec 27 18:41:47 ubuntu systemd[1]: Starting The Apache HTTP Server...
Dec 27 18:41:47 ubuntu apachectl[4275]: AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this mess
Dec 27 18:41:47 ubuntu systemd[1]: Started The Apache HTTP Server.

**Comment by SergiX44** [comment]
Your problem is related to your apache config. Also, you should download the release zip from the releases instead cloning the repo. Please follow the installation docs.
