### ISSUE TITLE
Filter, tag, and sort features possibly broken

### ISSUE THREAD

**Issue by ac820** [SergiX44/XBackBone#430]
This may be a docker container implementation issue, but I've seen this persist over a couple different container offerings that I've tried so wanted to raise it here to probe if there is known issue or resolution for this. Finding that these viewing features will appear as a query param and refresh the page upon using them, however the action of any of these query parameters doesn't have effect on the displayed records on the page.

Troubleshooting notes
- My last container provider dropped this one and I don't remember what it was, but get the same issue on the linuxserver.io container as of this morning. I believe both of these containers are using the latest release of this codebase
- using a reverse proxy to expose container, xbackbone container nginx .accesslog records show these query params were not surpressed
- no apparent error message shown from nginx logs or browser console debug
- attempted this with both mysql backend and sqllite with same results

Please let me know if I can provide anything else or info to help out; Thank you

![image](https://user-images.githubusercontent.com/502885/147508697-079a1193-2ea5-4e0c-ac62-4a3cb75f8fc5.png)

**Comment by SergiX44** [comment]
My instance is not running on docker, to me the click on the tag works fine. It's possibile that in the docker cofiguration the query params are not configured correcly

**Comment by darkzero-sdz** [comment]
I have the same issue with the recent linuxserver docker container. Whatever I try, it just doesn't sort.

**Comment by rubenixnagios** [comment]
same problem here on linuxserver.io docker image running armv7 (rpi 4 8GB) behind NPM as a reverse proxy
also attempted with both mysql and sqllite backends, same exact results
hope someone fins a fix!

**Comment by JohnFawkes** [comment]
ok so i have fixed this. Ill have to let linuxserver io know

stop the container and go to where you mounted the /config at and got to nginx/site-confs and open default


replace 
    location / {
        try_files $uri $uri/ /index.php;
    }

with

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

then restart the container. your welcome

**Comment by JohnFawkes** [comment]
Ive replied to the issue in linuxservers repo to let them know of the issue and how to fix

**Comment by JohnFawkes** [comment]
Its now fixed in linuxservers repo so when the container updates tags will now sort

**Comment by ac820** [comment]
@JohnFawkes That did it! Thank you for finding that and reaching out to LSIO to get that patched in their docker as well

**Comment by JohnFawkes** [comment]
> @JohnFawkes That did it! Thank you for finding that and reaching out to LSIO to get that patched in their docker as well

No problem! If I had known about this earlier I would of fixed it awhile ago. I've been using lsio xbackbone docker for like 7 months now and never noticed it. I just happened to randomly click a tag today and noticed the bug and then came here and saw others were having the same issue and then started comparing nginx configs and found the problem
