### ISSUE TITLE
Videos with .mov not playing without downloading

### ISSUE THREAD

**Issue by JohnFawkes** [SergiX44/XBackBone#442]
**System Info**
 Docker

**Describe the bug**
Opening any .mov file my users share via apple iPhone doesn't play. have to manually download to play via vlc or something like that

**To Reproduce**
1. Upload a .mov
2. Try playing

**Expected behavior**
To play the video without downloading

**Screenshots**
https://share.servernation.xyz/yOna3/NAKUpARu18.png
https://share.servernation.xyz/gUXi0/QEHOdUTA03.MOV

**Logs**
XBackBone and/or webserver logs.
Not sure how to get backbone logs with docker

**Comment by clownmoney** [comment]
.MOV is not supported by HTML5.
More can be read [here](https://stackoverflow.com/a/40999234).

An alternative is converting the .MOV files to a supported video type.

**Comment by luchontandil** [comment]
Neither the .mkv video files

**Comment by SergiX44** [comment]
Limited the player to files that are actually supported by browsers
