### ISSUE TITLE
Option to disable or make the image/file viewer page as secondary

### ISSUE THREAD

**Issue by Savasdotexe** [SergiX44/XBackBone#443]
**Is your feature request related to a problem? Please describe.**
I simply want to not have to type /raw everytime I want to copy the URL. The suggestion to add /raw within ShareX is not helpful, because I sometimes use XBackBone list to get the URL.

**Describe the solution you'd like**
I like the file viewer, sometimes videos/images/files are better approach this way, but I'd suggest that as a setting or the exact opposite adding a /viewer and the raw file as the first link by default.

**Comment by GabrielSerealia** [comment]
I would like to see this as well, I run into conflicts with some programs as they're expecting a .png extension to determine file type or in the case of Discord it wont play videos in previews.

https://i.serealia.ca/puGE3/saCiWugA02.webm

**Comment by Lewis8379** [comment]
I came here to suggest the exact same thing

**Comment by SergiX44** [comment]
Duplicated of https://github.com/SergiX44/XBackBone/issues/291

There is an option to copy the raw url from ui instead of the main one from the settings.
Maybe an option to switch between viewer and raw can be implemented in a future v4
