### ISSUE TITLE
Cloudflare Minimum TLS Version

### ISSUE THREAD

**Issue by ahatdude** [SergiX44/XBackBone#451]
**System Info**
+ Using the latest docker container
+ XBackBone Version: 3.5.1
+ Webserver: [Apache/Nginx/...]: Nginx Proxy Manager
+ Database backend: [SQLite/Mysql/...]: default SQLite

**Describe the bug**
I was battling with this for a while when I finally discovered that having the "Minimum TLS Version" on cloudflare at 1.3 essentially stops xbackbone from working.

**To Reproduce**
1. Go to 'Cloudflare.com'
2. Click on 'SSL/TLS -> Edge certificates'
3. Scroll down to 'Minimum TLS Version'
4. Change from 1.2 to 1.3 and give it a moment. Xbackbone will stop working (at least on sharex).

**Expected behavior**
I would expect it to work normally, as with TLS 1.2.

**Screenshots**
This is the error I get when on TLS 1.3 (I blurred out my URL)

![I8sTIAh0m2](https://user-images.githubusercontent.com/97416616/163156798-3c3365a0-5cda-4552-8373-7dcb9402f73f.png)

**Comment by SergiX44** [comment]
TLS is not managed in any way by the XBB, i don't think at this point that sharex supports tls 1.3 or by your nginx config
