### ISSUE TITLE
post_max_size = 0 confuse XBackBone

### ISSUE THREAD

**Issue by DBotThePony** [SergiX44/XBackBone#453]
**System Info**
+ PHP Version: 8.0.8
+ XBackBone Version: 3.5.1
+ Webserver: nginx
+ Database backend: MariaDB

**Describe the bug**
Setting `post_max_size` to `0` will [remove](https://www.php.net/manual/en/ini.core.php#ini.post-max-size) any limit on max post body size (because nginx handles this limit on it's own by `client_max_body_size`, and leave only PHP's `upload_max_filesize` for the files themselves), but for xbackbone it looks like max post size is effectively zero bytes, rejecting any upload requests with HTTP 400.

**To Reproduce**
1. Install PHP
2. Install XBackBone
3. Configure `post_max_size` to `0`
4. Have XBackBone report max upload size of `0B`
5. Have XBackBone reject with HTTP 400 any attempts to upload files

**Comment by SergiX44** [comment]
Mh thats interesting, need further investigation
