### ISSUE TITLE
Video Blackscreen but Sound works fine

### ISSUE THREAD

**Issue by Herobr1ne** [SergiX44/XBackBone#458]
Hello, I have the problem that since a few days almost every video is a blackscreen to see. The problem occurred with 2 xBackbone instances at the same time. Both instances are on the same server and also configured the same (except port).

[Example 1](https://media.niggofiggo.com/MaRA9/SIKAdoLa75.mp4)
[Example 2](https://upload.steven-arnold.eu/TiNU6/boMAqoja14.mp4)

The xBackbone Server is behind a reverse Proxy
For example 1 185.117.1.150:8081
For Example 2 185.117.1.150:8080

xBackbone v3.5.1
PHP Version: 7.4.26
Max memory usage: 1G
Max upload size:

    post_max_size: 20G
    upload_max_filesize: 20G

Hope, someone can help to fix the Problem

**Comment by Herobr1ne** [comment]
ah, and i already tryed to restart the Docker Comtainer. Both Container

**Comment by S0me6uy** [comment]
Same here

**Comment by Herobr1ne** [comment]
> Hello,
> 
> Same here : Hope we'll have explanations of what's happening ^^

I figured out, where the Problem is. Some video codecs are not Supported. The Blackscreen Video are rendered with nvec codec. Render it with x264 and it works fine :)
