### ISSUE TITLE
Installer error

### ISSUE THREAD

**Issue by CookieCr2nk** [SergiX44/XBackBone#46]
**System Info**
+ PHP Version: PHP 7.3.5
+ XBackBone Version: XBackBone 2.5.3
+ Webserver:  Apache/2.4.25
+ Cloudflare: I am using Cloudflare but i think this isn't the problem. 

**Describe the bug**
 After i click on configure and Install it comes this. "The config folder is not writable (/home/users/webspace/www/cdn.example.com/install/../config.php)" I had SQLite and gived the File Permissions with "chmod -R 777 *"

**To Reproduce**
1. Go to example.com/install
2. Click on Install

**Expected behavior**
I think it's and error in the installer.

**Screenshots**

**Comment by SergiX44** [comment]
Is not only about permissions, check that the folders are owned by the webserver user and the Php openbasedir is configured correctly.

**Comment by CookieCr2nk** [comment]
Thanks it work now. For any reason the file Owner was root. Now i wanted to install xBackbone with MySQL. After the install process on the login screen i saw following error.

`Cannot connect to the database: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes [42000] 
`

**Comment by SergiX44** [comment]
That is not XBackBone issue but a MariaDB/Mysql bad configuration (especially for versions <10.2, I had a similar problem)
Check out this: https://stackoverflow.com/a/38675910

**Comment by jalada** [comment]
For anyone coming to this now, I indeed had an old version of MariaDB on Ubuntu 18.04 and I fixed it by using the MariaDB repos: https://downloads.mariadb.org/mariadb/repositories/#mirror=one
