### ISSUE TITLE
Videos not always embedding on Discord (And fix)

### ISSUE THREAD

**Issue by Supositware** [SergiX44/XBackBone#469]
**Describe the bug**
Large videos does not always get embedded on Discord

**To Reproduce**
1. Upload a video larger than 8 mb
2. send the link on Discord and it may or may not embed

**Expected behavior**
Always embed

**Screenshots**
![raw](https://user-images.githubusercontent.com/36051669/173479968-941b348e-2ac5-4b29-b5d7-d3851aa40982.png)
(The same happens when appending /raw)
![raw](https://user-images.githubusercontent.com/36051669/173480641-b2dc320a-055d-4cd7-bd08-898b1f36def1.png)
(With the fix)

From what I tried it can be fixed by making it so videos always show an embed like the images and adding some more tags. I used the ones from [BetterTwitFix](https://github.com/dylanpdx/BetterTwitFix/blob/main/templates/video.html). Now the videos seems to reliably embed up to 100 mb, larger than that and it will load until it times out.

And changed the block meta from [resources/templates/upload/public.twig](https://github.com/SergiX44/XBackBone/tree/master/resources/templates/upload/public.twig)
I don't know if all the tags are necessary.
```twig
{% block meta %}
    <meta name="twitter:card" content="summary_large_image">
    <meta property="og:type" content="website"/>
    <meta id="embed-title" property="og:title" content="{{ media.filename }} ({{ media.size }})">
    <meta id="embed-desc" property="og:description" content="{{ lang('date') }}: {{ media.timestamp }}">
    {% if type == 'image' %}
        <meta id="embed-image" property="og:image" content="{{ url }}/raw">
        <meta id="discord" name="twitter:image" content="{{ url }}/raw">
        <meta id="image-src" name="twitter:image:src" content="{{ url }}/raw">
        <meta id="discord" name="twitter:image" content="{{ url }}/raw">
        <meta id="image-src" name="twitter:image:src" content="{{ url }}/raw">
    {% elseif type is same as ('video') %}
        <meta name="twitter:card" content="player" />
        <meta name="twitter:title" content="{{ media.filename }} ({{ media.size }})" />
        <meta name="twitter:image" content="0" />
        <meta name="twitter:player:width" content="720" />
        <meta name="twitter:player:height" content="480" />
        <meta name="twitter:player:stream" content="{{ url }}/raw" />
        <meta name="twitter:player:stream:content_type" content="video/mp4" />

        <meta property="og:url" content="{{ url }}/raw" />
        <meta property="og:video" content="{{ url }}/raw" />
        <meta property="og:video:secure_url" content="{{ url }}/raw" />
        <meta property="og:video:type" content="video/mp4" />
        <meta property="og:video:width" content="720" />
        <meta property="og:video:height" content="480" />
        <meta property="og:image" content="0" />
    {% endif %}
{% endblock %}

```
I removed Discord user agents from [app/Web/UA.php](https://github.com/SergiX44/XBackBone/tree/master/app/Web/UA.php) so it does not try to embed the raw video. Maybe having it as a toggle in the settings?

I've been able to reproduce it with a fresh install of xbackbone from the [linuxserver.io docker container](https://hub.docker.com/r/linuxserver/xbackbone).
I hope it is not an issue from my setup but if it is I apologize for creating the issue.

**Comment by SergiX44** [comment]
Thanks for the proposed fix, I'll look into that

**Comment by SergiX44** [comment]
I've implented kind of a workaround for this strange behaviour that discord has, if no embed enabled and the video is larger than 8mb, it forces the embedding in this commit https://github.com/SergiX44/XBackBone/commit/1979c3f3183f27c086d6c04335f645071d54014c
I'll be up with the next release.
