### ISSUE TITLE
Discord embed not working

### ISSUE THREAD

**Issue by Aiyzox** [SergiX44/XBackBone#478]
**System Info**
+ PHP Version: 7.4.26
+ XBackBone Version: 3.6.0
+ Webserver: nginx
+ Database backend: Mysql

**Describe the bug**
When you send screenshot image to discord there are not discord embed

**To Reproduce**
1. Take a screen with shareX or upload via webpannel
2. copy link
3. paste & send on discord
4. discord emped not apear, its just the image

**Expected behavior**
I need to have discord embed.

**Screenshots**
https://share.charlieg.fr/nIMi7/tiDIyuSO87.png

**Logs**
nginx error log empty

**Comment by Aiyzox** [comment]
I have find the error

**Comment by Kinyin** [comment]
Would you mind telling me how you found/fixed the error?
