### ISSUE TITLE
Large files cannot be uploaded

### ISSUE THREAD

**Issue by Yunmo-1** [SergiX44/XBackBone#518]
**System Info**
+ PHP Version: 7.4.33
+ XBackBone Version: v3.6.1
+ Webserver: IIS
+ Database backend: Mysql

**Describe the bug**
Larger files cannot be uploaded, the exact size has not been tested. Once uploaded, there is no response

**Screenshots**
![image](https://user-images.githubusercontent.com/79674967/219277762-41a2a40b-de34-4bf4-a407-d8ceed7ea8b8.png)

![image](https://user-images.githubusercontent.com/79674967/219278247-b5d7d609-d405-44a4-9b9f-7bde711ad40d.png)

**Comment by Yunmo-1** [comment]
It's stuck at 3% all the time

**Comment by SJ-Tom** [comment]
https://xbackbone.app/common_issues.html#how-to-increase-the-upload-max-file-size
