### ISSUE TITLE
Warning: require([redacted]/vendor/autoload.php): failed to open stream

### ISSUE THREAD

**Issue by JamesHawkinss** [SergiX44/XBackBone#54]
Hiya,

I'm using cPanel on a shared host. I'm trying to run the install script, but whenever I visit a page in this directory I'm getting errors complaining vendor/autoload.php. I know this has something to do with Composer, I wondered if you'd be able to shed more light on it?

I do not have SSH access to my webserver.

**Comment by SergiX44** [comment]
Is the [redacted]/vendor/autoload.php path correct?
The permission on the uploaded files are correct?

**Comment by JamesHawkinss** [comment]
Thanks for your response.

The file path would lead to the right place, but a /vendor folder hasn't been generated. I presume this is because cPanel doesn't like composer, or something.

If I was to chmod the whole folder, do you know what permissions I would give it? I could just give it 777 and see what happens? 

Do you happen to have the /vendor directory that you could just send me, so that I don't need to use composer for it to work?

**Comment by SergiX44** [comment]
The /vendor folder should be present in the release zip file and uploaded if you have a shared hosting.
Download the release zip from the github release page and try again (https://github.com/SergiX44/XBackBone/releases).

**Comment by JamesHawkinss** [comment]
Thanks so much! I'll try that and let you know how I get along :D

**Comment by JamesHawkinss** [comment]
Alright so I managed to run the installer and everything - but CSS doesn't seem to be working on the admin panel and stuff? 

Image: https://i.thedudeinthecorner.xyz/files/UuqmC.png

**Comment by SergiX44** [comment]
With the latest release: https://github.com/SergiX44/XBackBone/releases/tag/2.6
Is the static/ folder present and contains something?

**Comment by JamesHawkinss** [comment]
Yup it's there, and it has 7 folders within it.

**Comment by JamesHawkinss** [comment]
Made it work! Thanks for your help.
