### ISSUE TITLE
Call to undefined function App\Web\session_status() in /home/container/webroot/app/Web/Session.php:19

### ISSUE THREAD

**Issue by KrazyKleb** [sergix44/XBackBone#552]
**System Info**
+ PHP Version: IDK
+ XBackBone Version: 3.6.3
+ Webserver: Nginx
+ Database backend: SQLite

**Describe the bug**
FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function App\Web\session_status() in /home/container/webroot/app/Web/Session.php:19
Stack trace:
#0 /home/container/webroot/install/index.php(67): App\Web\Session->__construct()
#1 [internal function]: {closure}()
#2 /home/container/webroot/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()
#3 /home/container/webroot/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\Invoker->call()
#4 /home/container/webroot/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\FactoryResolver->resolve()
#5 /home/container/webroot/vendor/php-di/php-di/src/Container.php(390): DI\Definition\Resolver\ResolverDispatcher->resolve()
#6 /home/container/webroot/vendor/php-di/php-di/src/Container.php(139): DI\Container->resolveDefinition()
#7 /home/container/webroot/vendor/php-di/php-di/src/Definition/Reference.php(53): DI\Container->get()
#8 /home/container/webroot/vendor/ph" while reading response header from upstream, client: no, server: , request: "GET /install/ HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "no"
no - - [05/Dec/2023:21:06:38 +0000] "GET /install/ HTTP/1.1" 500 5 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0"

**To Reproduce**
Install it on an nginx webserver

**Expected behavior**
It works

**Screenshots**
![image](https://github.com/sergix44/XBackBone/assets/124646709/848e4b0c-694a-4992-9ff5-8910aed37727)

**Logs**
XBackBone and/or webserver logs.

**Comment by sergix44** [comment]
Without the PHP version is not sure, but 99/100 you are running on an unsupported php version, or at least without session support (?)
