### ISSUE TITLE
add invite key for auth

### ISSUE THREAD

**Issue by b00walk3r** [sergix44/XBackBone#555]
It would be great if a registration system with an invitation code could be added.

**Comment by SrS2225a** [comment]
XBackBone already supports this feature, you just need to enable it. Here are the steps:

1. In your admin account, go to System
2. In the System Settings, toggle registrations enabled to on
3. Apply the changes

**Comment by b00walk3r** [comment]
> XBackBone already supports this feature, you just need to enable it. Here are the steps:
> 
> 1. In your admin account, go to System
> 2. In the System Settings, toggle registrations enabled to on
> 3. Apply the changes

What I mean is that no one can register without an "invite code".

**Comment by sergix44** [comment]
Probably something that can be added for the v4 rewrite, but right now the closest thing instead of generate an invite code, you can create the account for them, and let them reset the password.
