### ISSUE TITLE
mp4 does not play in safari

### ISSUE THREAD

**Issue by gramakri** [sergix44/XBackBone#557]
**System Info**
+ PHP Version: 8.1 (hosted on Cloudron)
+ XBackBone Version: 3.6.3
+ Webserver: [Apache/Nginx/...] apache
+ Database backend: [SQLite/Mysql/...] MySQL

**Describe the bug**
Upload a mp4 file . The video does not play in Safari (on Desktop or iOS). It plays fine on all other browsers.

**To Reproduce**
1. Upload mp4. I used the mp4 in https://mobamotion.mobatek.net/samples/sample-mp4-video.html
2. Open link . It works everywhere except Safari
3. The video appears to be "stuck"

**Expected behavior**
mp4 video should play

**Comment by gramakri** [comment]
Some background - https://forum.cloudron.io/topic/10723/mp4-files-not-playing-in-safari-on-iphones

I was debugging this a bit. Initially, I thought this was because of "/raw" in the source URL. I renamed this to raw.mp4 but it doesn't need to matter for Safari.

It looks like there is some issue with the response XBackBone sends for content range requests. See https://stackoverflow.com/questions/30199261/why-wont-safari-play-file-without-extension-in-video , https://github.com/rwf2/Rocket/issues/806 , https://github.com/jooby-project/jooby/issues/523 and https://stackoverflow.com/questions/32996396/safari-9-0-can-not-play-mp4-video-on-the-storage-server for related issues. I am still debugging , will update this issue as I find any more info to add.

**Comment by gramakri** [comment]
Removing the `autoplay` tag for video makes it work on iphone. But it still doesn't work on desktop safari.

**Comment by gramakri** [comment]
FWIW, `playsinline` doesn't seem to help on desktop safari.

**Comment by sergix44** [comment]
I dont have any Apple device to test Safari sadly, if you find a way to make it work feel free to open a PR
