### ISSUE TITLE
docker image 3.7.0

### ISSUE THREAD

**Issue by DjSni** [sergix44/XBackBone#558]
**System Info**
+ Docker
+ XBackBone 3.7.0

**Describe the bug**
after updateing to the latest version i get the following error: 
```error
400 Bad Request
The server cannot or will not process the request due to an apparent client error.
```

**Logs**
```logs
Message: Bad request.
File: /app/www/public/app/Controllers/TagController.php
Line: 26
Trace: #0 [internal function]: App\Controllers\TagController->addTag()
#1 /app/www/public/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()
#2 /app/www/public/vendor/php-di/slim-bridge/src/ControllerInvoker.php(47): Invoker\Invoker->call()
#3 /app/www/public/vendor/slim/slim/Slim/Routing/Route.php(384): DI\Bridge\Slim\ControllerInvoker->__invoke()
#4 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#5 /app/www/public/app/Middleware/CheckForMaintenanceMiddleware.php(26): Slim\MiddlewareDispatcher->handle()
#6 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\CheckForMaintenanceMiddleware->__invoke()
#7 /app/www/public/app/Middleware/AuthMiddleware.php(33): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#8 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\AuthMiddleware->__invoke()
#9 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#10 /app/www/public/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#11 /app/www/public/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#12 /app/www/public/app/Middleware/InjectMiddleware.php(21): Slim\Routing\RouteRunner->handle()
#13 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\InjectMiddleware->__invoke()
#14 /app/www/public/app/Middleware/LangMiddleware.php(25): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\LangMiddleware->__invoke()
#16 /app/www/public/app/Middleware/RememberMiddleware.php(39): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#17 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\RememberMiddleware->__invoke()
#18 /app/www/public/bootstrap/app.php(105): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Closure->{closure}()
#20 /app/www/public/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#22 /app/www/public/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#24 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /app/www/public/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#26 /app/www/public/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#27 /app/www/public/index.php(11): Slim\App->run()
#28 {main}
Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor. [] []
[2024-01-14 16:23:23] app.ERROR: 400 Bad Request
Type: Slim\Exception\HttpBadRequestException
Code: 400
Message: Bad request.
File: /app/www/public/app/Controllers/TagController.php
Line: 26
Trace: #0 [internal function]: App\Controllers\TagController->addTag()
#1 /app/www/public/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()
#2 /app/www/public/vendor/php-di/slim-bridge/src/ControllerInvoker.php(47): Invoker\Invoker->call()
#3 /app/www/public/vendor/slim/slim/Slim/Routing/Route.php(384): DI\Bridge\Slim\ControllerInvoker->__invoke()
#4 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#5 /app/www/public/app/Middleware/CheckForMaintenanceMiddleware.php(26): Slim\MiddlewareDispatcher->handle()
#6 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\CheckForMaintenanceMiddleware->__invoke()
#7 /app/www/public/app/Middleware/AuthMiddleware.php(33): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#8 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\AuthMiddleware->__invoke()
#9 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#10 /app/www/public/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#11 /app/www/public/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#12 /app/www/public/app/Middleware/InjectMiddleware.php(21): Slim\Routing\RouteRunner->handle()
#13 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\InjectMiddleware->__invoke()
#14 /app/www/public/app/Middleware/LangMiddleware.php(25): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\LangMiddleware->__invoke()
#16 /app/www/public/app/Middleware/RememberMiddleware.php(39): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#17 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\RememberMiddleware->__invoke()
#18 /app/www/public/bootstrap/app.php(105): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Closure->{closure}()
#20 /app/www/public/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#22 /app/www/public/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#24 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /app/www/public/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#26 /app/www/public/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#27 /app/www/public/index.php(11): Slim\App->run()
#28 {main}
Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor. [] []
```

**Comment by iball** [comment]
I'm getting:

{"message":"Request without file attached.","version":"3.7.0"}

And all my snapshot pics are gone.

**Comment by sergix44** [comment]
I'm sorry but I dont ship the docker container directly, so without knowing how is configured is basically impossible to debug.
I've updated a couple of instances of mine (non docker, baremetal or vm) without any issues, so 🤷

**Comment by DjSni** [comment]
i have published a bug at linuxserver, i am closing this one.

**Comment by iball** [comment]
OK, looks like a new bug this time.  Everything works in the Docker image *except* when one goes to change the theme, then it throws a 500 error.

From the logs:

`Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor. [] []
[2024-01-15 10:39:48] app.INFO: User admin uploaded new media. ["98"] []
[2024-01-15 10:43:04] app.ERROR: 500 Internal Server Error
Type: Slim\Exception\HttpInternalServerErrorException
Code: 500
Message: Internal server error.
File: /app/www/public/app/Controllers/SettingController.php
Line: 84
Trace: #0 /app/www/public/app/Controllers/SettingController.php(50): App\Controllers\SettingController->applyTheme()
#1 [internal function]: App\Controllers\SettingController->saveSettings()
#2 /app/www/public/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()
#3 /app/www/public/vendor/php-di/slim-bridge/src/ControllerInvoker.php(47): Invoker\Invoker->call()
#4 /app/www/public/vendor/slim/slim/Slim/Routing/Route.php(384): DI\Bridge\Slim\ControllerInvoker->__invoke()
#5 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#6 /app/www/public/app/Middleware/AdminMiddleware.php(28): Slim\MiddlewareDispatcher->handle()
#7 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\AdminMiddleware->__invoke()
#8 /app/www/public/app/Middleware/CheckForMaintenanceMiddleware.php(26): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#9 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\CheckForMaintenanceMiddleware->__invoke()
#10 /app/www/public/app/Middleware/AuthMiddleware.php(33): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#11 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\AuthMiddleware->__invoke()
#12 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#13 /app/www/public/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#14 /app/www/public/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#15 /app/www/public/app/Middleware/InjectMiddleware.php(21): Slim\Routing\RouteRunner->handle()
#16 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\InjectMiddleware->__invoke()
#17 /app/www/public/app/Middleware/LangMiddleware.php(25): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#18 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\LangMiddleware->__invoke()
#19 /app/www/public/app/Middleware/RememberMiddleware.php(39): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#20 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\RememberMiddleware->__invoke()
#21 /app/www/public/bootstrap/app.php(105): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#22 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Closure->{closure}()
#23 /app/www/public/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#24 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#25 /app/www/public/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#26 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#27 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#28 /app/www/public/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#29 /app/www/public/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#30 /app/www/public/index.php(11): Slim\App->run()
#31 {main}
Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor. [] []
`
