### ISSUE TITLE
Cannot upload files larger than 100MB when using Cloudflare

### ISSUE THREAD

**Issue by SrS2225a** [sergix44/XBackBone#560]
**System Info**
+ PHP Version: 8.3.2
+ XBackBone Version: 3.7.0
+ Webserver: Nginx
+ Database backend: SQLite

**Describe the bug**
When using cloudflare for your site, when uploading files larger than 100MB, the file will fail to upload (even though XBackBone thinks it was successful), resulting in a http 413 error from cloudflare origin. This is because on the free cloudflare plan, the plan will limit the max file size you can upload in a single request.

**To Reproduce**
1. Go to the upload page
2. Choose a file and upload
3. Upon finishing, the file fails to upload

**Expected behavior**
The file gets uploaded to XBackBone, and shows in the home page, but does not. However, this is easy enough to fix by chunking the upload into something like 50MB parts or similar (see related article: https://community.cloudflare.com/t/large-file-upload-issue/493514). I think an option of some kind of toggle to use chunking will be beneficial for those that do need it and those that don't. I will see about adding chunking this weekend if I can. Thanks!

**Screenshots**
![Screenshot 2024-01-19 143226](https://github.com/sergix44/XBackBone/assets/22408517/8cc3eaad-4293-4d59-b77f-9bbf557a514d)

**Logs**
N\A

**Comment by SrS2225a** [comment]
Yeah, turns out it is way harder than I first initially thought that it would require some breaking changes to the backend, so because of that, I think that someone with more knowledge about this should do it instead :)

**Comment by rafalohaki** [comment]
uploading via website, it could be fixed with added upload in chunks

**Comment by SrS2225a** [comment]
Thanks, I did not know you could disable that by disabling the Cloudflare proxy. That did the trick, thank you
