### ISSUE TITLE
Thumbnails are not clickable in Table mode

### ISSUE THREAD

**Issue by gerroon** [SergiX44/XBackBone#72]
**System Info**
+ PHP Version: 7.1
+ XBackBone Version: 2.6.4
+ Webserver: Apache

It seems like the thumbnails in the table mode are not clickable at all, in fact there is no way to open a media item to see it in real size.

It would be nice if one can actually click to see in the table mode.

**Comment by SergiX44** [comment]
In the column of the actions, there is a link to open the preview.
![image](https://user-images.githubusercontent.com/4172890/64940870-69cf4a80-d865-11e9-8a10-57c55090a9df.png)

**Comment by gerroon** [comment]
Ok I see, I mean I do not see. That button is totally grayed out in the dark theme.

See yourself

I am using Darkly

https://i.imgur.com/1gxkLRL.png

**Comment by SergiX44** [comment]
Oh, yeah. Sadly not all bootswatch themes are perfect, some of those would require specific patches to look nice. Maybe try another dark theme.

**Comment by gerroon** [comment]
No problem, as long as the functionality is there it should be ok.
