### ISSUE TITLE
HTTP 500 error after clearing orphans

### ISSUE THREAD

**Issue by codemicro** [SergiX44/XBackBone#74]
**System Info**
+ PHP Version: 7.2
+ XBackBone Version: 2.6.4
+ Webserver: Apache2
+ Storage: Google Cloud bucket

**Describe the bug**
After deleting a user and clearing orphaned files, every page in the UI (bar the login and view screenshot page) returns a HTTP 500 error (it's worth noting that you can still upload and view files).

**To Reproduce**
1. Make a user.
2. Upload images to user.
3. Delete user.
4. Delete orphaned images.
4. See error on reload of page

**Expected behavior**
Y'know.... to work? 😅 

**Screenshots**
https://www.tdpain.net/sharex/suxE1/DoNOYEFite503.png (see, still works!)

**Comment by SergiX44** [comment]
Can you attach the log files form the logs directory to the issue?

**Comment by codemicro** [comment]
There is nothing in the Apache logs, I should have mentioned.

Probably not the best idea to have plaintext passwords in the log file.

[log-2019-09-17.txt](https://github.com/SergiX44/XBackBone/files/3622832/log-2019-09-17.txt)

**Comment by SergiX44** [comment]
When the v2.6.5 is up, you should manually update, and then navigate to the url `http://<URL>/system/deleteOrphanFiles` manually to fix the issue.
