### ISSUE TITLE
FR: Auto categories

### ISSUE THREAD

**Issue by gerroon** [SergiX44/XBackBone#75]
Hi

It would be great if ther eis a way to categorize the uploads automatically by predefined filters and by custom user created filters. For instance there could images, videos, gifs, files along with months, weeks etc.

**Comment by gerroon** [comment]
Categgorizes can be  like folders too, I am not talking about tagging them, although as long long as clicking on a tag displays only those items might work too.

**Comment by skinit** [comment]
I vote for this too ... would be a very useful tag & search feature
