### ISSUE TITLE
FR: Alternative url for the raw files

### ISSUE THREAD

**Issue by gerroon** [SergiX44/XBackBone#78]
Hi

Is it possible to create alternative url for the raw downloads? Because the current method fails in some applications whe previewing the images.

This url fails in some apps

`https://DOMAIN/sharex/e2e3e/MOkisOYa740.png/raw`

It would nice if we could set an alternative method  like below so that all apps can grab the files properly if they rely on file name formatting

`https://DOMAIN/sharex/e2e3e/MOkisOYa740_RAW.png` 

thanks

**Comment by Fma965** [comment]
hmm it seems something is stopping discord and facebook etc showing previews, any ideas why?
https://cypix.xyz/Cemu9/JiSOnidUyo097.png/raw <--- random image for testing

**Comment by SergiX44** [comment]
Discord, facebook, telegram etc, are recognized by xbackbone and should return the image as preview. If you have Cloudflare enabled please check your anti robot configuration.
