### ISSUE TITLE
Check if mod_rewrite is enabled

### ISSUE THREAD

**Issue by scharfschiesser** [SergiX44/XBackBone#84]
**Is your feature request related to a problem? Please describe.**
As I was looking through the closed issues it seems like I'm not the only person who had [this issue](https://github.com/SergiX44/XBackBone/issues/83).

**Describe the solution you'd like**
In order to avoid problems like the one mentioned above you could implement a simple addition to the installer that checks if the apache2 module `mod_rewrite` is enabled.

**Additional context**
I'm not good at php by any means but I found this:
If `in_array('mod_rewrite', apache_get_modules())` returns true then it's enabled.

**Comment by SergiX44** [comment]
If you are running apache, with php running via mod_php, it's ok. But, with nginx with fpm, IIS? Or even apache with fastcgi or fpm it's the same problem, you cannot detect it without some dirty workarounds, and there are so many different, equally valid, configurations. Is something out of the app context how the webserver is rewriting the urls.
