### ISSUE TITLE
Filename and path name the same?

### ISSUE THREAD

**Issue by Dinip** [SergiX44/XBackBone#85]
**System Info**
+ PHP Version: 7.2.24
+ XBackBone Version: 2.6.6
+ Webserver: Apache2

For me would be better to have the same filename and storage path name, for example, my shareX generates a random 10 char name for every screenshot that I take, saves the screenshot on a local folder and sends it to my webserver running XBackBone which generates a new name for web access. https://domain.com/userCode/a9b8c7.png instead of the name that the file had (a1b2c3.png). Is there any way to have the same name on both sides?

**Screenshots**
![T6bTaNGqa1](https://user-images.githubusercontent.com/8941012/67639045-1845c100-f8e3-11e9-84d0-17c808b26a5a.png)

**Comment by SergiX44** [comment]
The question is not very clear, but I try to explain anyway: the filename is the original file name you have uploaded. If you download that file from xbackbone, the original name will be used to instruct your browser to use that name. The storage path is where the file is on the storage media, that can be the local disk, aws, etc.
The original file name is not used in the storage dir to avoid name collisions, and for an easy 1:1 conversion of an url to return a media file.
No, at the moment you can't change the behaviour, and renaming the file in the table column will create inconsistencies between the storage and the database.
