### ISSUE TITLE
Any possible way to use this on Android?

### ISSUE THREAD

**Issue by gerroon** [SergiX44/XBackBone#87]
Hi

I realize there is no Android app but I am wondering if there is a way to send files drom Android using some ways? It seems like it all takes to send some command to some the server. I ran out of ideas. Maybe someone has a decent idea to get this working so one can send screenshots via share to the possible solution which would upload the screen to the server.

**Comment by SergiX44** [comment]
From version 3.0, web uploading is available. I also want to evaluate whether an implementation as a progressive web app can improve the user experience.
