### ISSUE TITLE
500 internal server error loading gallery/images

### ISSUE THREAD

**Issue by Maddiiee** [SergiX44/XBackBone#89]
**System Info**
+ PHP Version: 7.2
+ XBackBone Version: latest
+ Webserver: not sure i use namecheap, cant figure out what it use

**Describe the bug**
When I go to gallery or any image i get 500 internal server error

**To Reproduce**

**Expected behavior**
For it to work

**Screenshot**
https://i.imgur.com/11qeti4.png

**Log**
https://pastebin.com/raw/mdwf521W

**Comment by SergiX44** [comment]
The PHP `fileinfo` extension is missing, check if you can enable it from your control panel.

**Comment by Maddiiee** [comment]
Thank you, sorry for the silly thread
