### ISSUE TITLE
Upgrade fails

### ISSUE THREAD

**Issue by gerroon** [SergiX44/XBackBone#93]
**Describe the bug**
Just tried to upgrade to release-v3.0.RC1  it via the web ui and this is what I get `500 Internal Server Error`

I then tried the manual update without much luck.

```
Apache Version 	Apache/2.4.41 (Debian)
Apache API Version 	20120211 
```

Please see the logs
https://paste.debian.net/hidden/9aa8291e/

**Comment by gerroon** [comment]
Btw it is probably a good idea if the web upgrade process makes some backups before going forward in case people are not in a position to back up their stuff. Ideally people should back their server stuff regularly. 

I had a backup so it is not an issue for me.

**Comment by SergiX44** [comment]
Did you updated the database?
The logs show that database migrations have not been installed.

**Comment by gerroon** [comment]
Well the web install did not do any upgrade itself, it pretty much failed right away, I did not have any issues with the web upgrade befoee like this.

I will see how I can do manual upgrade with the database stuff.

**Comment by gerroon** [comment]
How do I do the database upgrade wiht manual upgrade? Because when I copy the files then goto /install all I get is a n empty page

**Comment by SergiX44** [comment]
From the web ui you should click update on the system settings, wait for redirect to the installer, click update database and it's done.
To manually update without using the installer, just overwrite the files, and run the `bin/migrate` command from the cli.

**Comment by gerroon** [comment]
Thanks, I will try it.

What I am trying to say is that the web installer does not do any kind of redirect to installer it fails right away with a white page. When I try to goto install I get server error page.

**Comment by gerroon** [comment]
Ok I tried the manual upgrade and I still get page 404

here is from the browser console

```
Source map error: Error: request failed with status 404
Resource URL: https://XXXXX.com/XXX/static/bootstrap/css/bootstrap.min.css?1573861428
Source Map URL: bootstrap.min.css.map


```

**Comment by DNCD** [comment]
I'm getting those too after upgrade


```
[2019-11-16 23:07:38] app.CRITICAL: Slim Application Error:
Type: Slim\Exception\HttpNotFoundException
Code: 404
Message: Not found.
File: /home/admin001/domains/domain.com/public_html/i/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 91
Trace: #0 /home/admin001/domains/domain.com/public_html/i/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(57): Slim\Middleware\RoutingMiddleware->performRouting(Object(GuzzleHttp\Psr7\ServerRequest))
#1 /home/admin001/domains/domain.com/public_html/i/vendor/slim/slim/Slim/MiddlewareDispatcher.php(132): Slim\Middleware\RoutingMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(class@anonymous))
#2 /home/admin001/domains/domain.com/public_html/i/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(89): class@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#3 /home/admin001/domains/domain.com/public_html/i/vendor/slim/slim/Slim/MiddlewareDispatcher.php(132): Slim\Middleware\ErrorMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(class@anonymous))
#4 /home/admin001/domains/domain.com/public_html/i/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): class@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#5 /home/admin001/domains/domain.com/public_html/i/vendor/slim/slim/Slim/App.php(208): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#6 /home/admin001/domains/domain.com/public_html/i/vendor/slim/slim/Slim/App.php(192): Slim\App->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#7 /home/admin001/domains/domain.com/public_html/i/index.php(9): Slim\App->run()
#8 {main}
View in rendered output by enabling the "displayErrorDetails" setting.
 [] []

```

**Comment by DNCD** [comment]
I was able to fix the issue in my main domain .htaccess had some redirect mod_rewrite which wasn't allowing me to finalize my upgrade

**Comment by gerroon** [comment]
Well the thing is this used to work I mean installled the initial version and did couple upgrades via the web. My setup has ever been the same. Why is it failing now? 

Also the manual upgrade fails for me as well.

**Comment by DNCD** [comment]
> Well the thing is this used to work I mean installled the initial version and did couple upgrades via the web. My setup has ever been the same. Why is it failing now?
> 
> Also the manual upgrade fails for me as well.


are you using a subdomain? if you do check your .htaccess for the main domain.

**Comment by gerroon** [comment]
I am not using a subdomain but it is running under a subpath. Like I said I have been using it without any issues with upgrades, if I had a redirect issue I would have that with the current version too, but it is a speculation until the dev explains how to go forward with this.

Both the web upgrade and the manual upgrade fails for  me.

**Comment by SergiX44** [comment]
> I am not using a subdomain but it is running under a subpath. Like I said I have been using it without any issues with upgrades, if I had a redirect issue I would have that with the current version too, but it is a speculation until the dev explains how to go forward with this.
> 
> Both the web upgrade and the manual upgrade fails for me.

I haven't tested subpath since the slim upgrade, that can be an issue.
