### ISSUE TITLE
3.0 RC2 upgrade resetted the token

### ISSUE THREAD

**Issue by gerroon** [SergiX44/XBackBone#95]
**System Info**
+ PHP Version:  7.1.20-1 
+ XBackBone Version: 3.0 RC2 
+ Webserver: Apache/2.4.41 (Debian) 
+ Database backend: Sqlte

I was finally able to upgrade to 3 after the new fix. But I see that the new update deleted the existing token, generally this is not a n issue but it makes scripted situations complicated because I had to replace that token in 3 different linux ends and couple Windows pcs. 

While this is not that big of a deal but this can fail uploads without noticing.

It tried to paste the existing one back in the user profile ui  but that  does not seem to work.

thanks

**Comment by SergiX44** [comment]
The tokens are not user-editable.
The update process doesn't touch the stored users or change the stored data, in this specific case (v3) only add two columns and a table. 
Check the access logs or try to give more details.
