### ISSUE TITLE
RESPONSE in the bash script returns a cut off link

### ISSUE THREAD

**Issue by gerroon** [SergiX44/XBackBone#96]
Here what I get with the current v3.0 RC2

`curl -s -F "token=token_XXXXX" -F "upload=@FILE.jpg" https://xxx.xxx/xback/upload`

`"message":"OK.","version":"3.0.RC2","url":"\/xback\/929c5\/PikIfIPI07.jpg"}`

As you see  the url is trucated and no longer provides the full url

Also the new script does not use the full url for curl, hre is the portion from the generated script

`RESPONSE="$(curl -s -F "token=XXXXX" -F "upload=@${1}" /xback/upload)";`

**Comment by SergiX44** [comment]
It's a known issue, there is still some problems with url generation due to upgrade to slim 4 (which the docs are pretty bad or not updated).

**Comment by gerroon** [comment]
Sure but does that mean that it will be broken as is or a fix on the way given that you closed the bug?

**Comment by SergiX44** [comment]
Fixed in RC3.

**Comment by gerroon** [comment]
I see thank you. I will test it
