### ISSUE TITLE
Resume-able Upload & Download Support

### ISSUE THREAD

**Issue by draft1** [SergiX44/XBackBone#98]
This is a great feature for File Sharing App.
Thanks!

**Comment by SergiX44** [comment]
The current dropzone library doesn't include the option to pause the upload, so really possible to implement resumable uploads.

**Comment by draft1** [comment]
I thought it can be done with this:
https://gitlab.com/meno/dropzone/wikis/faq#chunked-uploads

**Comment by SergiX44** [comment]
Writing partial chunks and finally reassemble them when using remote storages (ex: S3, Dropbox, etc) could be painfully slow, without a local file cache.
At the moment I don't think I am implementing something like this. Meanwhile, I close the issue, if someone wants to propose an implementation, they can send a PR.

**Comment by evanmn** [comment]
I am not currently prepared to attempt an implementation, but I would check out [tus.io](https://tus.io/). It seems to have an implementation figured out and is used in PsiTransfer.
